"""baseline schema

Revision ID: 0001
Revises:
Create Date: 2026-09-02 09:40:48.193936
"""
from typing import Sequence, Union

import app.models.base
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_settings'))
    )
    op.create_index(op.f('ix_app_settings_key'), 'app_settings', ['key'], unique=True)
    op.create_table('interest_tags',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('deprecated', sa.Boolean(), nullable=False),
    sa.Column('kind', sa.String(length=20), server_default='topic', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interest_tags'))
    )
    op.create_index(op.f('ix_interest_tags_category'), 'interest_tags', ['category'], unique=False)
    op.create_index(op.f('ix_interest_tags_key'), 'interest_tags', ['key'], unique=True)
    op.create_index(op.f('ix_interest_tags_kind'), 'interest_tags', ['kind'], unique=False)
    op.create_table('job_families',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('path', sa.String(length=300), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['job_families.id'], name=op.f('fk_job_families_parent_id_job_families'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_families'))
    )
    op.create_index(op.f('ix_job_families_key'), 'job_families', ['key'], unique=True)
    op.create_index(op.f('ix_job_families_path'), 'job_families', ['path'], unique=False)
    op.create_table('job_sources',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('connector_key', sa.String(length=80), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', app.models.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('sync_state', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(connector_key) BETWEEN 1 AND 80', name=op.f('ck_job_sources_connector_key_present')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_sources'))
    )
    op.create_index(op.f('ix_job_sources_key'), 'job_sources', ['key'], unique=True)
    op.create_table('notification_kinds',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('group', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('default_enabled', sa.Boolean(), nullable=False),
    sa.Column('default_channels', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('mutable', sa.Boolean(), nullable=False),
    sa.Column('manage_url', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_kinds'))
    )
    op.create_index(op.f('ix_notification_kinds_key'), 'notification_kinds', ['key'], unique=True)
    op.create_table('organizations',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=200), nullable=True),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('proposed', 'active', 'deprecated')", name=op.f('ck_organizations_status_allowed')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_index(op.f('ix_organizations_key'), 'organizations', ['key'], unique=True)
    op.create_table('skills',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('level_anchors', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['skills.id'], name=op.f('fk_skills_parent_id_skills'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills'))
    )
    op.create_index(op.f('ix_skills_category'), 'skills', ['category'], unique=False)
    op.create_index(op.f('ix_skills_key'), 'skills', ['key'], unique=True)
    op.create_index(op.f('ix_skills_status'), 'skills', ['status'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', app.models.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ai_generations',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('task_type', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('prompt', sa.String(length=4000), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_generations_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_generations'))
    )
    op.create_index(op.f('ix_ai_generations_task_type'), 'ai_generations', ['task_type'], unique=False)
    op.create_index(op.f('ix_ai_generations_user_id'), 'ai_generations', ['user_id'], unique=False)
    op.create_table('ai_providers',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('provider_type', sa.String(length=40), nullable=False),
    sa.Column('api_base', sa.String(length=500), nullable=False),
    sa.Column('api_key_encrypted', sa.String(length=600), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_providers_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_providers')),
    sa.UniqueConstraint('scope', 'user_id', 'name', name='uq_ai_providers_scope_user_name')
    )
    op.create_index(op.f('ix_ai_providers_scope'), 'ai_providers', ['scope'], unique=False)
    op.create_index(op.f('ix_ai_providers_user_id'), 'ai_providers', ['user_id'], unique=False)
    op.create_table('assessment_templates',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('author_user_id', sa.Uuid(), nullable=True),
    sa.Column('author_key', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('audience_stages', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('ref', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retired', sa.Boolean(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('bank', 'ai', 'user', 'imported')", name=op.f('ck_assessment_templates_source_allowed')),
    sa.CheckConstraint("status IN ('draft', 'published', 'retired')", name=op.f('ck_assessment_templates_status_allowed')),
    sa.CheckConstraint("visibility IN ('private', 'unlisted', 'public')", name=op.f('ck_assessment_templates_visibility_allowed')),
    sa.CheckConstraint('version >= 1', name=op.f('ck_assessment_templates_version_positive')),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], name=op.f('fk_assessment_templates_author_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_templates')),
    sa.UniqueConstraint('author_key', 'key', 'version', name='uq_assessment_templates_version'),
    sa.UniqueConstraint('ref', name=op.f('uq_assessment_templates_ref'))
    )
    op.create_index(op.f('ix_assessment_templates_author_user_id'), 'assessment_templates', ['author_user_id'], unique=False)
    op.create_index('ix_assessment_templates_key', 'assessment_templates', ['key'], unique=False)
    op.create_table('background_jobs',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('job_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=200), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('claimed_at', app.models.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', app.models.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', app.models.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_background_jobs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_background_jobs'))
    )
    op.create_index('ix_background_jobs_status_created', 'background_jobs', ['status', 'created_at'], unique=False)
    op.create_index('ix_background_jobs_user_id', 'background_jobs', ['user_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_sessions'))
    )
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('mime', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=False),
    sa.Column('extraction', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_documents_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_table('experience_items',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=True),
    sa.Column('org_name', sa.String(length=200), nullable=False),
    sa.Column('start', sa.Date(), nullable=False),
    sa.Column('end', sa.Date(), nullable=True),
    sa.Column('open_ended', sa.Boolean(), nullable=False),
    sa.Column('hours_per_week', sa.Integer(), nullable=True),
    sa.Column('onsite_policy', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('links', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('job', 'project', 'internship', 'volunteer', 'freelance')", name=op.f('ck_experience_items_kind_allowed')),
    sa.CheckConstraint("status IN ('draft', 'active')", name=op.f('ck_experience_items_status_allowed')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_experience_items_org_id_organizations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_experience_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experience_items'))
    )
    op.create_index(op.f('ix_experience_items_user_id'), 'experience_items', ['user_id'], unique=False)
    op.create_index('ix_experience_items_user_status', 'experience_items', ['user_id', 'status'], unique=False)
    op.create_table('jobs',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('links', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('ai_metadata', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_jobs_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['family_id'], ['job_families.id'], name=op.f('fk_jobs_family_id_job_families'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index(op.f('ix_jobs_code'), 'jobs', ['code'], unique=True)
    op.create_index(op.f('ix_jobs_family_id'), 'jobs', ['family_id'], unique=False)
    op.create_index(op.f('ix_jobs_source'), 'jobs', ['source'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('learning_resources',
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('cost', sa.String(length=20), nullable=False),
    sa.Column('level_target', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("cost IN ('free', 'freemium', 'paid')", name=op.f('ck_learning_resources_cost_allowed')),
    sa.CheckConstraint("kind IN ('course', 'book', 'cert', 'doc', 'video')", name=op.f('ck_learning_resources_kind_allowed')),
    sa.CheckConstraint("status IN ('draft', 'published')", name=op.f('ck_learning_resources_status_allowed')),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_learning_resources_skill_id_skills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_resources'))
    )
    op.create_index('ix_learning_resources_skill_id', 'learning_resources', ['skill_id'], unique=False)
    op.create_table('notification_kind_prefs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind_id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('channels', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kind_id'], ['notification_kinds.id'], name=op.f('fk_notification_kind_prefs_kind_id_notification_kinds'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_kind_prefs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_kind_prefs')),
    sa.UniqueConstraint('user_id', 'kind_id', name='uq_notification_kind_prefs')
    )
    op.create_index(op.f('ix_notification_kind_prefs_user_id'), 'notification_kind_prefs', ['user_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('desktop_channel_enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_preferences')),
    sa.UniqueConstraint('user_id', name='uq_notification_preferences_user')
    )
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=False)
    op.create_table('notification_rules',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('fit_threshold', 'new_in_family', 'new_posting_match')", name=op.f('ck_notification_rules_kind_supported')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_rules_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_rules')),
    sa.UniqueConstraint('user_id', 'kind', name='uq_notification_rules_user_kind')
    )
    op.create_index(op.f('ix_notification_rules_user_id'), 'notification_rules', ['user_id'], unique=False)
    op.create_table('notification_subscriptions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.String(length=120), nullable=False),
    sa.Column('endpoint', sa.String(length=1000), nullable=False),
    sa.Column('endpoint_hash', sa.String(length=64), nullable=False),
    sa.Column('p256dh', sa.String(length=200), nullable=False),
    sa.Column('auth', sa.String(length=200), nullable=False),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_subscriptions')),
    sa.UniqueConstraint('user_id', 'device_id', name='uq_notification_subs_device')
    )
    op.create_index(op.f('ix_notification_subscriptions_user_id'), 'notification_subscriptions', ['user_id'], unique=False)
    op.create_index('uq_notification_subs_endpoint', 'notification_subscriptions', ['endpoint_hash'], unique=True, sqlite_where=sa.text('is_active = 1'), postgresql_where=sa.text('is_active'))
    op.create_table('notifications',
    sa.Column('kind_id', sa.Uuid(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('source_ref', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('dedup_key', sa.String(length=150), nullable=True),
    sa.Column('dedup_expires_at', app.models.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kind_id'], ['notification_kinds.id'], name=op.f('fk_notifications_kind_id_notification_kinds'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_kind_created', 'notifications', ['kind_id', 'created_at'], unique=False)
    op.create_index('uq_notifications_dedup_key', 'notifications', ['dedup_key'], unique=True, sqlite_where=sa.text('dedup_key IS NOT NULL'), postgresql_where=sa.text('dedup_key IS NOT NULL'))
    op.create_table('profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('basics', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('academics', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('hobbies', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('likes', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('dislikes', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('aspirations', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('work_preferences', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('ai_summary', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles'))
    )
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    op.create_table('schedules',
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('task', sa.String(length=40), nullable=True),
    sa.Column('trigger', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('next_run_at', app.models.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', app.models.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=30), nullable=True),
    sa.Column('last_job_id', sa.Uuid(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('misfire_policy', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('system_source_sync', 'system_digest', 'system_demand_import', 'system_refit_sweep', 'user_saved_search', 'user_checkin')", name=op.f('ck_schedules_kind_allowed')),
    sa.CheckConstraint("misfire_policy IN ('asap', 'skip', 'next_slot')", name=op.f('ck_schedules_misfire_allowed')),
    sa.CheckConstraint("task IS NULL OR task IN ('posting_sync', 'digest', 'saved_search_run', 'fit_refit')", name=op.f('ck_schedules_task_allowed')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_schedules_owner_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedules')),
    sa.UniqueConstraint('kind', 'owner_user_id', 'payload_hash', name='uq_schedules_kind_owner_payload')
    )
    op.create_index('ix_schedules_next_run', 'schedules', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_schedules_owner_user_id'), 'schedules', ['owner_user_id'], unique=False)
    op.create_table('search_history',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('filters_hash', sa.String(length=64), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('saved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("scope IN ('catalog', 'rankings', 'universities', 'postings')", name=op.f('ck_search_history_scope_allowed')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_search_history_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_history'))
    )
    op.create_index(op.f('ix_search_history_scope'), 'search_history', ['scope'], unique=False)
    op.create_index(op.f('ix_search_history_user_id'), 'search_history', ['user_id'], unique=False)
    op.create_index('ix_search_history_user_saved', 'search_history', ['user_id', 'saved'], unique=False)
    op.create_table('universities',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('university_type', sa.String(length=20), nullable=False),
    sa.Column('website', sa.String(length=300), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_universities_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_universities')),
    sa.UniqueConstraint('name', 'country', name='uq_universities_name_country')
    )
    op.create_index(op.f('ix_universities_country'), 'universities', ['country'], unique=False)
    op.create_index(op.f('ix_universities_name'), 'universities', ['name'], unique=False)
    op.create_table('user_interests',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('interest_tag_id', sa.Uuid(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('weight >= 1 AND weight <= 5', name=op.f('ck_user_interests_weight_range')),
    sa.ForeignKeyConstraint(['interest_tag_id'], ['interest_tags.id'], name=op.f('fk_user_interests_interest_tag_id_interest_tags'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_interests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_interests')),
    sa.UniqueConstraint('user_id', 'interest_tag_id', name='uq_user_interests_user_tag')
    )
    op.create_index('ix_user_interests_interest_tag_id', 'user_interests', ['interest_tag_id'], unique=False)
    op.create_table('user_skills',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('level >= 1 AND level <= 10', name=op.f('ck_user_skills_level_range')),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_user_skills_skill_id_skills'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_skills_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_skills')),
    sa.UniqueConstraint('user_id', 'skill_id', name='uq_user_skills_user_skill')
    )
    op.create_index('ix_user_skills_skill_id', 'user_skills', ['skill_id'], unique=False)
    op.create_table('ai_models',
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], name=op.f('fk_ai_models_provider_id_ai_providers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_models'))
    )
    op.create_index(op.f('ix_ai_models_provider_id'), 'ai_models', ['provider_id'], unique=False)
    op.create_table('assessment_runs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('phase_order', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_phase', sa.Integer(), nullable=False),
    sa.Column('progress', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['assessment_templates.id'], name=op.f('fk_assessment_runs_template_id_assessment_templates'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_assessment_runs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_runs'))
    )
    op.create_index(op.f('ix_assessment_runs_status'), 'assessment_runs', ['status'], unique=False)
    op.create_index(op.f('ix_assessment_runs_user_id'), 'assessment_runs', ['user_id'], unique=False)
    op.create_table('career_paths',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_career_paths_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_career_paths'))
    )
    op.create_index(op.f('ix_career_paths_job_id'), 'career_paths', ['job_id'], unique=False)
    op.create_index(op.f('ix_career_paths_status'), 'career_paths', ['status'], unique=False)
    op.create_table('chat_messages',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name=op.f('fk_chat_messages_session_id_chat_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('departments',
    sa.Column('university_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('field_key', sa.String(length=80), nullable=False),
    sa.Column('degree', sa.String(length=20), nullable=False),
    sa.Column('duration_years', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=30), nullable=False),
    sa.Column('application_deadline', sa.Date(), nullable=True),
    sa.Column('tuition', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], name=op.f('fk_departments_university_id_universities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('university_id', 'name', name='uq_departments_uni_name')
    )
    op.create_index(op.f('ix_departments_field_key'), 'departments', ['field_key'], unique=False)
    op.create_index(op.f('ix_departments_university_id'), 'departments', ['university_id'], unique=False)
    op.create_table('experience_achievements',
    sa.Column('experience_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('metric', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experience_items.id'], name=op.f('fk_experience_achievements_experience_id_experience_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experience_achievements'))
    )
    op.create_index(op.f('ix_experience_achievements_experience_id'), 'experience_achievements', ['experience_id'], unique=False)
    op.create_table('experience_skills',
    sa.Column('experience_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('role_in_item', sa.String(length=20), nullable=False),
    sa.Column('level_claim', sa.Integer(), nullable=True),
    sa.Column('last_used', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role_in_item IN ('primary', 'secondary', 'exposure')", name=op.f('ck_experience_skills_role_allowed')),
    sa.CheckConstraint('level_claim IS NULL OR (level_claim >= 1 AND level_claim <= 10)', name=op.f('ck_experience_skills_level_claim_range')),
    sa.ForeignKeyConstraint(['experience_id'], ['experience_items.id'], name=op.f('fk_experience_skills_experience_id_experience_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_experience_skills_skill_id_skills'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experience_skills')),
    sa.UniqueConstraint('experience_id', 'skill_id', name='uq_experience_skills_pair')
    )
    op.create_index(op.f('ix_experience_skills_skill_id'), 'experience_skills', ['skill_id'], unique=False)
    op.create_table('growth_plans',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('target_job_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', app.models.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['target_job_id'], ['jobs.id'], name=op.f('fk_growth_plans_target_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_growth_plans_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_growth_plans')),
    sa.UniqueConstraint('user_id', 'target_job_id', name='uq_growth_plans_user_job')
    )
    op.create_index(op.f('ix_growth_plans_status'), 'growth_plans', ['status'], unique=False)
    op.create_index(op.f('ix_growth_plans_user_id'), 'growth_plans', ['user_id'], unique=False)
    op.create_table('job_postings',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=300), nullable=False),
    sa.Column('ref', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('org', sa.String(length=200), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=True),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('seniority', sa.String(length=20), nullable=True),
    sa.Column('employment_type', sa.String(length=20), nullable=True),
    sa.Column('contract_type', sa.String(length=60), nullable=True),
    sa.Column('onsite_policy', sa.String(length=20), nullable=True),
    sa.Column('work_hours', sa.String(length=60), nullable=True),
    sa.Column('hours_per_week_min', sa.Float(), nullable=True),
    sa.Column('hours_per_week_max', sa.Float(), nullable=True),
    sa.Column('travel_class', sa.String(length=60), nullable=True),
    sa.Column('education_level', sa.String(length=40), nullable=True),
    sa.Column('salary_currency', sa.String(length=3), nullable=True),
    sa.Column('salary_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_period', sa.String(length=10), nullable=True),
    sa.Column('posted_at', app.models.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('expires_at', app.models.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('extract', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('extract_version', sa.Integer(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('posting_facts', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('catalog_job_id', sa.Uuid(), nullable=True),
    sa.Column('mapping_method', sa.String(length=20), nullable=True),
    sa.Column('mapping_confidence', sa.Float(), nullable=True),
    sa.Column('mapping_reason', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('new', 'mapped', 'expired', 'hidden')", name=op.f('ck_job_postings_status_allowed')),
    sa.CheckConstraint('salary_min IS NULL OR salary_max IS NULL OR salary_min <= salary_max', name=op.f('ck_job_postings_salary_range_sane')),
    sa.ForeignKeyConstraint(['catalog_job_id'], ['jobs.id'], name=op.f('fk_job_postings_catalog_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_job_postings_org_id_organizations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['job_sources.id'], name=op.f('fk_job_postings_source_id_job_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_postings')),
    sa.UniqueConstraint('ref', name=op.f('uq_job_postings_ref')),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_postings_source_external')
    )
    op.create_index(op.f('ix_job_postings_org_id'), 'job_postings', ['org_id'], unique=False)
    op.create_index(op.f('ix_job_postings_seniority'), 'job_postings', ['seniority'], unique=False)
    op.create_index('ix_postings_catalog_job', 'job_postings', ['catalog_job_id'], unique=False)
    op.create_index('ix_postings_expires_at', 'job_postings', ['expires_at'], unique=False)
    op.create_index('ix_postings_salary_min', 'job_postings', ['salary_min'], unique=False)
    op.create_index('ix_postings_status_posted', 'job_postings', ['status', 'posted_at'], unique=False)
    op.create_table('job_relations',
    sa.Column('from_job_id', sa.Uuid(), nullable=False),
    sa.Column('to_job_id', sa.Uuid(), nullable=False),
    sa.Column('relation_type', sa.String(length=40), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_job_id'], ['jobs.id'], name=op.f('fk_job_relations_from_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_job_id'], ['jobs.id'], name=op.f('fk_job_relations_to_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_relations')),
    sa.UniqueConstraint('from_job_id', 'to_job_id', 'relation_type', name='uq_job_relation_edge')
    )
    op.create_index('ix_job_relations_from', 'job_relations', ['from_job_id'], unique=False)
    op.create_index(op.f('ix_job_relations_relation_type'), 'job_relations', ['relation_type'], unique=False)
    op.create_index(op.f('ix_job_relations_source'), 'job_relations', ['source'], unique=False)
    op.create_index('ix_job_relations_to', 'job_relations', ['to_job_id'], unique=False)
    op.create_table('job_skills',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('required_level', sa.Integer(), nullable=False),
    sa.Column('importance', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('required_level >= 1 AND required_level <= 10', name=op.f('ck_job_skills_required_level_range')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_skills_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_job_skills_skill_id_skills'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_skills')),
    sa.UniqueConstraint('job_id', 'skill_id', name='uq_job_skills_job_skill')
    )
    op.create_index('ix_job_skills_skill_id', 'job_skills', ['skill_id'], unique=False)
    op.create_table('job_tags',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('interest_tag_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interest_tag_id'], ['interest_tags.id'], name=op.f('fk_job_tags_interest_tag_id_interest_tags'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_tags_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_tags')),
    sa.UniqueConstraint('job_id', 'interest_tag_id', name='uq_job_tags_job_tag')
    )
    op.create_index('ix_job_tags_interest_tag_id', 'job_tags', ['interest_tag_id'], unique=False)
    op.create_table('match_insights',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('ai_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=False),
    sa.Column('ai_positives', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('ai_negatives', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('prerequisites', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('ai_model', sa.String(length=80), nullable=False),
    sa.Column('ai_generated_at', app.models.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('fit_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('fit_breakdown', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('fit_version', sa.Integer(), nullable=False),
    sa.Column('user_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('user_notes', sa.Text(), nullable=False),
    sa.Column('seen_at', app.models.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('saved_at', app.models.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('hidden_at', app.models.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_match_insights_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_match_insights_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_insights')),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_match_user_job')
    )
    op.create_index(op.f('ix_match_insights_job_id'), 'match_insights', ['job_id'], unique=False)
    op.create_index(op.f('ix_match_insights_status'), 'match_insights', ['status'], unique=False)
    op.create_index(op.f('ix_match_insights_user_id'), 'match_insights', ['user_id'], unique=False)
    op.create_table('notification_deliveries',
    sa.Column('notification_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.String(length=1000), nullable=True),
    sa.Column('subscription_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel IN ('in_app', 'desktop', 'browser')", name=op.f('ck_notification_deliveries_channel_allowed')),
    sa.CheckConstraint("status IN ('pending', 'sent', 'delivered', 'failed')", name=op.f('ck_notification_deliveries_status_allowed')),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], name=op.f('fk_notification_deliveries_notification_id_notifications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['notification_subscriptions.id'], name=op.f('fk_notification_deliveries_subscription_id_notification_subscriptions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_deliveries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_deliveries')),
    sa.UniqueConstraint('notification_id', 'user_id', 'channel', name='uq_notification_deliveries_triple')
    )
    op.create_index('ix_notification_deliveries_user_channel', 'notification_deliveries', ['user_id', 'channel', 'created_at'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_user_id'), 'notification_deliveries', ['user_id'], unique=False)
    op.create_table('notification_recipients',
    sa.Column('notification_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('read_at', app.models.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('dismissed_at', app.models.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('unread', 'read', 'dismissed')", name=op.f('ck_notification_recipients_status_allowed')),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], name=op.f('fk_notification_recipients_notification_id_notifications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_recipients_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_recipients')),
    sa.UniqueConstraint('notification_id', 'user_id', name='uq_notification_recipients_pair')
    )
    op.create_index(op.f('ix_notification_recipients_user_id'), 'notification_recipients', ['user_id'], unique=False)
    op.create_index('ix_notification_recipients_user_status', 'notification_recipients', ['user_id', 'status'], unique=False)
    op.create_table('ai_task_assignments',
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('provider_id', sa.Uuid(), nullable=True),
    sa.Column('model_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], name=op.f('fk_ai_task_assignments_model_id_ai_models'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], name=op.f('fk_ai_task_assignments_provider_id_ai_providers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_task_assignments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_task_assignments'))
    )
    op.create_index(op.f('ix_ai_task_assignments_scope'), 'ai_task_assignments', ['scope'], unique=False)
    op.create_index(op.f('ix_ai_task_assignments_task_type'), 'ai_task_assignments', ['task_type'], unique=False)
    op.create_index(op.f('ix_ai_task_assignments_user_id'), 'ai_task_assignments', ['user_id'], unique=False)
    op.create_table('assessment_questions',
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('phase', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('help', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('time_split', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('audience_stages', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('sort_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['assessment_runs.id'], name=op.f('fk_assessment_questions_run_id_assessment_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_questions'))
    )
    op.create_index(op.f('ix_assessment_questions_run_id'), 'assessment_questions', ['run_id'], unique=False)
    op.create_index(op.f('ix_assessment_questions_status'), 'assessment_questions', ['status'], unique=False)
    op.create_table('career_path_steps',
    sa.Column('path_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=True),
    sa.Column('skill_id', sa.Uuid(), nullable=True),
    sa.Column('education_level', sa.String(length=30), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('optional', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['job_families.id'], name=op.f('fk_career_path_steps_family_id_job_families'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['path_id'], ['career_paths.id'], name=op.f('fk_career_path_steps_path_id_career_paths'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_career_path_steps_skill_id_skills'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_career_path_steps')),
    sa.UniqueConstraint('path_id', 'position', name='uq_career_path_steps_position')
    )
    op.create_table('department_admissions',
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('baseline_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('top_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('quota', sa.Integer(), nullable=True),
    sa.Column('units', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_department_admissions_department_id_departments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_department_admissions_document_id_documents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_department_admissions')),
    sa.UniqueConstraint('department_id', 'year', 'source', name='uq_admissions_dept_year_source')
    )
    op.create_index(op.f('ix_department_admissions_department_id'), 'department_admissions', ['department_id'], unique=False)
    op.create_index(op.f('ix_department_admissions_year'), 'department_admissions', ['year'], unique=False)
    op.create_table('job_department_links',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('required_subjects', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('typical_position', sa.String(length=200), nullable=False),
    sa.Column('salary_band', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('employment_rate_pct', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_job_department_links_department_id_departments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_department_links_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_department_links')),
    sa.UniqueConstraint('job_id', 'department_id', name='uq_job_department')
    )
    op.create_index(op.f('ix_job_department_links_department_id'), 'job_department_links', ['department_id'], unique=False)
    op.create_index(op.f('ix_job_department_links_job_id'), 'job_department_links', ['job_id'], unique=False)
    op.create_table('posting_fits',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('posting_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('breakdown', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('inputs_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['posting_id'], ['job_postings.id'], name=op.f('fk_posting_fits_posting_id_job_postings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_posting_fits_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posting_fits')),
    sa.UniqueConstraint('user_id', 'posting_id', name='uq_posting_fits_user_posting')
    )
    op.create_index('ix_posting_fits_posting_id', 'posting_fits', ['posting_id'], unique=False)
    op.create_table('posting_interactions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('posting_id', sa.Uuid(), nullable=False),
    sa.Column('seen_at', app.models.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('saved_at', app.models.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('hidden_at', app.models.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('applied_at', app.models.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('applied_via_url', sa.String(length=1000), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['posting_id'], ['job_postings.id'], name=op.f('fk_posting_interactions_posting_id_job_postings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_posting_interactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posting_interactions')),
    sa.UniqueConstraint('user_id', 'posting_id', name='uq_posting_interactions_user_posting')
    )
    op.create_index('ix_posting_interactions_posting_id', 'posting_interactions', ['posting_id'], unique=False)
    op.create_table('posting_skills',
    sa.Column('posting_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('evidence', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('required_level', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('required_level IS NULL OR (required_level >= 1 AND required_level <= 10)', name=op.f('ck_posting_skills_required_level_range')),
    sa.ForeignKeyConstraint(['posting_id'], ['job_postings.id'], name=op.f('fk_posting_skills_posting_id_job_postings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_posting_skills_skill_id_skills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posting_skills')),
    sa.UniqueConstraint('posting_id', 'skill_id', name='uq_posting_skills_posting_skill')
    )
    op.create_index('ix_posting_skills_skill_id', 'posting_skills', ['skill_id'], unique=False)
    op.create_table('skill_evidence',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('assessment_run_id', sa.Uuid(), nullable=True),
    sa.Column('experience_item_id', sa.Uuid(), nullable=True),
    sa.Column('cv_document_id', sa.Uuid(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.Column('level_value', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('claimed_at', app.models.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('((CASE WHEN assessment_run_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN experience_item_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN cv_document_id IS NOT NULL THEN 1 ELSE 0 END)) = 1', name=op.f('ck_skill_evidence_one_source_set')),
    sa.ForeignKeyConstraint(['assessment_run_id'], ['assessment_runs.id'], name=op.f('fk_skill_evidence_assessment_run_id_assessment_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cv_document_id'], ['documents.id'], name=op.f('fk_skill_evidence_cv_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['experience_item_id'], ['experience_items.id'], name=op.f('fk_skill_evidence_experience_item_id_experience_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_skill_evidence_skill_id_skills'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_skill_evidence_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_evidence'))
    )
    op.create_index(op.f('ix_skill_evidence_user_id'), 'skill_evidence', ['user_id'], unique=False)
    op.create_index('ix_skill_evidence_user_skill', 'skill_evidence', ['user_id', 'skill_id'], unique=False)
    op.create_table('assessment_answers',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('answer', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('derived', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['assessment_questions.id'], name=op.f('fk_assessment_answers_question_id_assessment_questions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['assessment_runs.id'], name=op.f('fk_assessment_answers_run_id_assessment_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_answers')),
    sa.UniqueConstraint('run_id', 'question_id', name='uq_assessment_answers_run_question')
    )
    op.create_index(op.f('ix_assessment_answers_run_id'), 'assessment_answers', ['run_id'], unique=False)
    op.create_table('growth_plan_steps',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=True),
    sa.Column('path_step_id', sa.Uuid(), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('target_level', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_level', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('skill', 'experience', 'certification', 'education')", name=op.f('ck_growth_plan_steps_kind_allowed')),
    sa.CheckConstraint("status IN ('todo', 'doing', 'done', 'skipped')", name=op.f('ck_growth_plan_steps_status_allowed')),
    sa.CheckConstraint('target_level IS NULL OR (target_level >= 1 AND target_level <= 10)', name=op.f('ck_growth_plan_steps_target_level_range')),
    sa.ForeignKeyConstraint(['path_step_id'], ['career_path_steps.id'], name=op.f('fk_growth_plan_steps_path_step_id_career_path_steps'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['growth_plans.id'], name=op.f('fk_growth_plan_steps_plan_id_growth_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_growth_plan_steps_skill_id_skills'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_growth_plan_steps')),
    sa.UniqueConstraint('plan_id', 'position', name='uq_growth_plan_steps_plan_pos')
    )
    op.create_index('ix_growth_plan_steps_plan_id', 'growth_plan_steps', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_growth_plan_steps_plan_id', table_name='growth_plan_steps')
    op.drop_table('growth_plan_steps')
    op.drop_index(op.f('ix_assessment_answers_run_id'), table_name='assessment_answers')
    op.drop_table('assessment_answers')
    op.drop_index('ix_skill_evidence_user_skill', table_name='skill_evidence')
    op.drop_index(op.f('ix_skill_evidence_user_id'), table_name='skill_evidence')
    op.drop_table('skill_evidence')
    op.drop_index('ix_posting_skills_skill_id', table_name='posting_skills')
    op.drop_table('posting_skills')
    op.drop_index('ix_posting_interactions_posting_id', table_name='posting_interactions')
    op.drop_table('posting_interactions')
    op.drop_index('ix_posting_fits_posting_id', table_name='posting_fits')
    op.drop_table('posting_fits')
    op.drop_index(op.f('ix_job_department_links_job_id'), table_name='job_department_links')
    op.drop_index(op.f('ix_job_department_links_department_id'), table_name='job_department_links')
    op.drop_table('job_department_links')
    op.drop_index(op.f('ix_department_admissions_year'), table_name='department_admissions')
    op.drop_index(op.f('ix_department_admissions_department_id'), table_name='department_admissions')
    op.drop_table('department_admissions')
    op.drop_table('career_path_steps')
    op.drop_index(op.f('ix_assessment_questions_status'), table_name='assessment_questions')
    op.drop_index(op.f('ix_assessment_questions_run_id'), table_name='assessment_questions')
    op.drop_table('assessment_questions')
    op.drop_index(op.f('ix_ai_task_assignments_user_id'), table_name='ai_task_assignments')
    op.drop_index(op.f('ix_ai_task_assignments_task_type'), table_name='ai_task_assignments')
    op.drop_index(op.f('ix_ai_task_assignments_scope'), table_name='ai_task_assignments')
    op.drop_table('ai_task_assignments')
    op.drop_index('ix_notification_recipients_user_status', table_name='notification_recipients')
    op.drop_index(op.f('ix_notification_recipients_user_id'), table_name='notification_recipients')
    op.drop_table('notification_recipients')
    op.drop_index(op.f('ix_notification_deliveries_user_id'), table_name='notification_deliveries')
    op.drop_index('ix_notification_deliveries_user_channel', table_name='notification_deliveries')
    op.drop_table('notification_deliveries')
    op.drop_index(op.f('ix_match_insights_user_id'), table_name='match_insights')
    op.drop_index(op.f('ix_match_insights_status'), table_name='match_insights')
    op.drop_index(op.f('ix_match_insights_job_id'), table_name='match_insights')
    op.drop_table('match_insights')
    op.drop_index('ix_job_tags_interest_tag_id', table_name='job_tags')
    op.drop_table('job_tags')
    op.drop_index('ix_job_skills_skill_id', table_name='job_skills')
    op.drop_table('job_skills')
    op.drop_index('ix_job_relations_to', table_name='job_relations')
    op.drop_index(op.f('ix_job_relations_source'), table_name='job_relations')
    op.drop_index(op.f('ix_job_relations_relation_type'), table_name='job_relations')
    op.drop_index('ix_job_relations_from', table_name='job_relations')
    op.drop_table('job_relations')
    op.drop_index('ix_postings_status_posted', table_name='job_postings')
    op.drop_index('ix_postings_salary_min', table_name='job_postings')
    op.drop_index('ix_postings_expires_at', table_name='job_postings')
    op.drop_index('ix_postings_catalog_job', table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_seniority'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_org_id'), table_name='job_postings')
    op.drop_table('job_postings')
    op.drop_index(op.f('ix_growth_plans_user_id'), table_name='growth_plans')
    op.drop_index(op.f('ix_growth_plans_status'), table_name='growth_plans')
    op.drop_table('growth_plans')
    op.drop_index(op.f('ix_experience_skills_skill_id'), table_name='experience_skills')
    op.drop_table('experience_skills')
    op.drop_index(op.f('ix_experience_achievements_experience_id'), table_name='experience_achievements')
    op.drop_table('experience_achievements')
    op.drop_index(op.f('ix_departments_university_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_field_key'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_career_paths_status'), table_name='career_paths')
    op.drop_index(op.f('ix_career_paths_job_id'), table_name='career_paths')
    op.drop_table('career_paths')
    op.drop_index(op.f('ix_assessment_runs_user_id'), table_name='assessment_runs')
    op.drop_index(op.f('ix_assessment_runs_status'), table_name='assessment_runs')
    op.drop_table('assessment_runs')
    op.drop_index(op.f('ix_ai_models_provider_id'), table_name='ai_models')
    op.drop_table('ai_models')
    op.drop_index('ix_user_skills_skill_id', table_name='user_skills')
    op.drop_table('user_skills')
    op.drop_index('ix_user_interests_interest_tag_id', table_name='user_interests')
    op.drop_table('user_interests')
    op.drop_index(op.f('ix_universities_name'), table_name='universities')
    op.drop_index(op.f('ix_universities_country'), table_name='universities')
    op.drop_table('universities')
    op.drop_index('ix_search_history_user_saved', table_name='search_history')
    op.drop_index(op.f('ix_search_history_user_id'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_scope'), table_name='search_history')
    op.drop_table('search_history')
    op.drop_index(op.f('ix_schedules_owner_user_id'), table_name='schedules')
    op.drop_index('ix_schedules_next_run', table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index('uq_notifications_dedup_key', table_name='notifications', sqlite_where=sa.text('dedup_key IS NOT NULL'), postgresql_where=sa.text('dedup_key IS NOT NULL'))
    op.drop_index('ix_notifications_kind_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('uq_notification_subs_endpoint', table_name='notification_subscriptions', sqlite_where=sa.text('is_active = 1'), postgresql_where=sa.text('is_active'))
    op.drop_index(op.f('ix_notification_subscriptions_user_id'), table_name='notification_subscriptions')
    op.drop_table('notification_subscriptions')
    op.drop_index(op.f('ix_notification_rules_user_id'), table_name='notification_rules')
    op.drop_table('notification_rules')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_notification_kind_prefs_user_id'), table_name='notification_kind_prefs')
    op.drop_table('notification_kind_prefs')
    op.drop_index('ix_learning_resources_skill_id', table_name='learning_resources')
    op.drop_table('learning_resources')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_source'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_family_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_code'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_experience_items_user_status', table_name='experience_items')
    op.drop_index(op.f('ix_experience_items_user_id'), table_name='experience_items')
    op.drop_table('experience_items')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index('ix_background_jobs_user_id', table_name='background_jobs')
    op.drop_index('ix_background_jobs_status_created', table_name='background_jobs')
    op.drop_table('background_jobs')
    op.drop_index('ix_assessment_templates_key', table_name='assessment_templates')
    op.drop_index(op.f('ix_assessment_templates_author_user_id'), table_name='assessment_templates')
    op.drop_table('assessment_templates')
    op.drop_index(op.f('ix_ai_providers_user_id'), table_name='ai_providers')
    op.drop_index(op.f('ix_ai_providers_scope'), table_name='ai_providers')
    op.drop_table('ai_providers')
    op.drop_index(op.f('ix_ai_generations_user_id'), table_name='ai_generations')
    op.drop_index(op.f('ix_ai_generations_task_type'), table_name='ai_generations')
    op.drop_table('ai_generations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_skills_status'), table_name='skills')
    op.drop_index(op.f('ix_skills_key'), table_name='skills')
    op.drop_index(op.f('ix_skills_category'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_organizations_key'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_notification_kinds_key'), table_name='notification_kinds')
    op.drop_table('notification_kinds')
    op.drop_index(op.f('ix_job_sources_key'), table_name='job_sources')
    op.drop_table('job_sources')
    op.drop_index(op.f('ix_job_families_path'), table_name='job_families')
    op.drop_index(op.f('ix_job_families_key'), table_name='job_families')
    op.drop_table('job_families')
    op.drop_index(op.f('ix_interest_tags_kind'), table_name='interest_tags')
    op.drop_index(op.f('ix_interest_tags_key'), table_name='interest_tags')
    op.drop_index(op.f('ix_interest_tags_category'), table_name='interest_tags')
    op.drop_table('interest_tags')
    op.drop_index(op.f('ix_app_settings_key'), table_name='app_settings')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
