"""initial schema

Revision ID: 046bb23aac42
Revises:
Create Date: 2026-08-28 02:32:18.751518
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models.base import StructuredJSON

revision: str = "046bb23aac42"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "interest_tags",
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("category", sa.String(length=60), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interest_tags")),
    )
    op.create_index(
        op.f("ix_interest_tags_category"), "interest_tags", ["category"], unique=False
    )
    op.create_index(op.f("ix_interest_tags_key"), "interest_tags", ["key"], unique=True)
    op.create_table(
        "job_families",
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("path", sa.String(length=300), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["job_families.id"],
            name=op.f("fk_job_families_parent_id_job_families"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_families")),
    )
    op.create_index(op.f("ix_job_families_key"), "job_families", ["key"], unique=True)
    op.create_index(
        op.f("ix_job_families_path"), "job_families", ["path"], unique=False
    )
    op.create_table(
        "skill_tags",
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("category", sa.String(length=60), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skill_tags")),
    )
    op.create_index(
        op.f("ix_skill_tags_category"), "skill_tags", ["category"], unique=False
    )
    op.create_index(op.f("ix_skill_tags_key"), "skill_tags", ["key"], unique=True)
    op.create_table(
        "users",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "ai_generations",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("task_type", sa.String(length=40), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("model", sa.String(length=80), nullable=False),
        sa.Column("prompt", sa.String(length=4000), nullable=False),
        sa.Column("output", StructuredJSON, nullable=True),
        sa.Column("tokens_in", sa.Integer(), nullable=True),
        sa.Column("tokens_out", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error", sa.String(length=1000), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_ai_generations_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_generations")),
    )
    op.create_index(
        op.f("ix_ai_generations_task_type"),
        "ai_generations",
        ["task_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_generations_user_id"), "ai_generations", ["user_id"], unique=False
    )
    op.create_table(
        "chat_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("context", StructuredJSON, nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_chat_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_sessions")),
    )
    op.create_index(
        op.f("ix_chat_sessions_user_id"), "chat_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "documents",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("filename", sa.String(length=300), nullable=False),
        sa.Column("mime", sa.String(length=120), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error", sa.String(length=500), nullable=False),
        sa.Column("extraction", StructuredJSON, nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_documents_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
    )
    op.create_index(op.f("ix_documents_status"), "documents", ["status"], unique=False)
    op.create_index(
        op.f("ix_documents_user_id"), "documents", ["user_id"], unique=False
    )
    op.create_table(
        "jobs",
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("short_description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("attributes", StructuredJSON, nullable=False),
        sa.Column("ai_metadata", StructuredJSON, nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_jobs_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["job_families.id"],
            name=op.f("fk_jobs_family_id_job_families"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    op.create_index(op.f("ix_jobs_code"), "jobs", ["code"], unique=True)
    op.create_index(op.f("ix_jobs_family_id"), "jobs", ["family_id"], unique=False)
    op.create_index(op.f("ix_jobs_source"), "jobs", ["source"], unique=False)
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_table(
        "profiles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("basics", StructuredJSON, nullable=False),
        sa.Column("academics", StructuredJSON, nullable=False),
        sa.Column("interests", StructuredJSON, nullable=False),
        sa.Column("hobbies", StructuredJSON, nullable=False),
        sa.Column("likes", StructuredJSON, nullable=False),
        sa.Column("dislikes", StructuredJSON, nullable=False),
        sa.Column("aspirations", StructuredJSON, nullable=False),
        sa.Column("work_preferences", StructuredJSON, nullable=False),
        sa.Column("constraints", StructuredJSON, nullable=False),
        sa.Column("ai_summary", StructuredJSON, nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profiles")),
    )
    op.create_index(op.f("ix_profiles_user_id"), "profiles", ["user_id"], unique=True)
    op.create_table(
        "universities",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("country", sa.String(length=80), nullable=False),
        sa.Column("city", sa.String(length=80), nullable=False),
        sa.Column("university_type", sa.String(length=20), nullable=False),
        sa.Column("website", sa.String(length=300), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_universities_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_universities")),
        sa.UniqueConstraint("name", "country", name="uq_universities_name_country"),
    )
    op.create_index(
        op.f("ix_universities_country"), "universities", ["country"], unique=False
    )
    op.create_index(
        op.f("ix_universities_name"), "universities", ["name"], unique=False
    )
    op.create_table(
        "chat_messages",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("metadata_json", StructuredJSON, nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["chat_sessions.id"],
            name=op.f("fk_chat_messages_session_id_chat_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_messages")),
    )
    op.create_index(
        op.f("ix_chat_messages_session_id"),
        "chat_messages",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "departments",
        sa.Column("university_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("field_key", sa.String(length=80), nullable=False),
        sa.Column("degree", sa.String(length=20), nullable=False),
        sa.Column("duration_years", sa.Integer(), nullable=False),
        sa.Column("language", sa.String(length=30), nullable=False),
        sa.Column("tuition", StructuredJSON, nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["university_id"],
            ["universities.id"],
            name=op.f("fk_departments_university_id_universities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_departments")),
        sa.UniqueConstraint("university_id", "name", name="uq_departments_uni_name"),
    )
    op.create_index(
        op.f("ix_departments_field_key"), "departments", ["field_key"], unique=False
    )
    op.create_index(
        op.f("ix_departments_university_id"),
        "departments",
        ["university_id"],
        unique=False,
    )
    op.create_table(
        "job_relations",
        sa.Column("from_job_id", sa.Uuid(), nullable=False),
        sa.Column("to_job_id", sa.Uuid(), nullable=False),
        sa.Column("relation_type", sa.String(length=40), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["from_job_id"],
            ["jobs.id"],
            name=op.f("fk_job_relations_from_job_id_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_job_id"],
            ["jobs.id"],
            name=op.f("fk_job_relations_to_job_id_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_relations")),
        sa.UniqueConstraint(
            "from_job_id", "to_job_id", "relation_type", name="uq_job_relation_edge"
        ),
    )
    op.create_index(
        "ix_job_relations_from", "job_relations", ["from_job_id"], unique=False
    )
    op.create_index(
        op.f("ix_job_relations_relation_type"),
        "job_relations",
        ["relation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_relations_source"), "job_relations", ["source"], unique=False
    )
    op.create_index("ix_job_relations_to", "job_relations", ["to_job_id"], unique=False)
    op.create_table(
        "match_insights",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("ai_score", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("ai_confidence", sa.Float(), nullable=True),
        sa.Column("ai_summary", sa.Text(), nullable=False),
        sa.Column("ai_positives", StructuredJSON, nullable=False),
        sa.Column("ai_negatives", StructuredJSON, nullable=False),
        sa.Column("prerequisites", StructuredJSON, nullable=False),
        sa.Column("ai_model", sa.String(length=80), nullable=False),
        sa.Column("ai_generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("base_score", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("user_score", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("user_notes", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_match_insights_job_id_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_match_insights_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match_insights")),
        sa.UniqueConstraint("user_id", "job_id", name="uq_match_user_job"),
    )
    op.create_index(
        op.f("ix_match_insights_job_id"), "match_insights", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_match_insights_status"), "match_insights", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_match_insights_user_id"), "match_insights", ["user_id"], unique=False
    )
    op.create_table(
        "department_admissions",
        sa.Column("department_id", sa.Uuid(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("baseline_score", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("top_score", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("quota", sa.Integer(), nullable=True),
        sa.Column("units", sa.String(length=40), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_department_admissions_department_id_departments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_department_admissions_document_id_documents"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_department_admissions")),
        sa.UniqueConstraint(
            "department_id", "year", "source", name="uq_admissions_dept_year_source"
        ),
    )
    op.create_index(
        op.f("ix_department_admissions_department_id"),
        "department_admissions",
        ["department_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_department_admissions_year"),
        "department_admissions",
        ["year"],
        unique=False,
    )
    op.create_table(
        "job_department_links",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("department_id", sa.Uuid(), nullable=False),
        sa.Column("relevance", sa.Float(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("required_subjects", StructuredJSON, nullable=False),
        sa.Column("typical_position", sa.String(length=200), nullable=False),
        sa.Column("salary_band", StructuredJSON, nullable=True),
        sa.Column("employment_rate_pct", sa.Float(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_job_department_links_department_id_departments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_job_department_links_job_id_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_department_links")),
        sa.UniqueConstraint("job_id", "department_id", name="uq_job_department"),
    )
    op.create_index(
        op.f("ix_job_department_links_department_id"),
        "job_department_links",
        ["department_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_department_links_job_id"),
        "job_department_links",
        ["job_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_job_department_links_job_id"), table_name="job_department_links"
    )
    op.drop_index(
        op.f("ix_job_department_links_department_id"), table_name="job_department_links"
    )
    op.drop_table("job_department_links")
    op.drop_index(
        op.f("ix_department_admissions_year"), table_name="department_admissions"
    )
    op.drop_index(
        op.f("ix_department_admissions_department_id"),
        table_name="department_admissions",
    )
    op.drop_table("department_admissions")
    op.drop_index(op.f("ix_match_insights_user_id"), table_name="match_insights")
    op.drop_index(op.f("ix_match_insights_status"), table_name="match_insights")
    op.drop_index(op.f("ix_match_insights_job_id"), table_name="match_insights")
    op.drop_table("match_insights")
    op.drop_index("ix_job_relations_to", table_name="job_relations")
    op.drop_index(op.f("ix_job_relations_source"), table_name="job_relations")
    op.drop_index(op.f("ix_job_relations_relation_type"), table_name="job_relations")
    op.drop_index("ix_job_relations_from", table_name="job_relations")
    op.drop_table("job_relations")
    op.drop_index(op.f("ix_departments_university_id"), table_name="departments")
    op.drop_index(op.f("ix_departments_field_key"), table_name="departments")
    op.drop_table("departments")
    op.drop_index(op.f("ix_chat_messages_session_id"), table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index(op.f("ix_universities_name"), table_name="universities")
    op.drop_index(op.f("ix_universities_country"), table_name="universities")
    op.drop_table("universities")
    op.drop_index(op.f("ix_profiles_user_id"), table_name="profiles")
    op.drop_table("profiles")
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_source"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_family_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_code"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_documents_user_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_status"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_chat_sessions_user_id"), table_name="chat_sessions")
    op.drop_table("chat_sessions")
    op.drop_index(op.f("ix_ai_generations_user_id"), table_name="ai_generations")
    op.drop_index(op.f("ix_ai_generations_task_type"), table_name="ai_generations")
    op.drop_table("ai_generations")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_skill_tags_key"), table_name="skill_tags")
    op.drop_index(op.f("ix_skill_tags_category"), table_name="skill_tags")
    op.drop_table("skill_tags")
    op.drop_index(op.f("ix_job_families_path"), table_name="job_families")
    op.drop_index(op.f("ix_job_families_key"), table_name="job_families")
    op.drop_table("job_families")
    op.drop_index(op.f("ix_interest_tags_key"), table_name="interest_tags")
    op.drop_index(op.f("ix_interest_tags_category"), table_name="interest_tags")
    op.drop_table("interest_tags")
    # ### end Alembic commands ###
