"""ai providers models assignments + user is_admin

Revision ID: 6866a6e415f3
Revises: adb43f0e25b4
Create Date: 2026-08-28 12:20:40.676931
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "6866a6e415f3"
down_revision: Union[str, None] = "adb43f0e25b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_providers",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("scope", sa.String(length=20), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("provider_type", sa.String(length=40), nullable=False),
        sa.Column("api_base", sa.String(length=500), nullable=False),
        sa.Column("api_key_encrypted", sa.String(length=600), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_ai_providers_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_providers")),
        sa.UniqueConstraint(
            "scope", "user_id", "name", name="uq_ai_providers_scope_user_name"
        ),
    )
    op.create_index(
        op.f("ix_ai_providers_scope"), "ai_providers", ["scope"], unique=False
    )
    op.create_index(
        op.f("ix_ai_providers_user_id"), "ai_providers", ["user_id"], unique=False
    )
    op.create_table(
        "ai_models",
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("model_name", sa.String(length=200), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=True),
        sa.Column("max_tokens", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["ai_providers.id"],
            name=op.f("fk_ai_models_provider_id_ai_providers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_models")),
    )
    op.create_index(
        op.f("ix_ai_models_provider_id"), "ai_models", ["provider_id"], unique=False
    )
    op.create_table(
        "ai_task_assignments",
        sa.Column("task_type", sa.String(length=50), nullable=False),
        sa.Column("scope", sa.String(length=20), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("provider_id", sa.Uuid(), nullable=True),
        sa.Column("model_id", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["ai_models.id"],
            name=op.f("fk_ai_task_assignments_model_id_ai_models"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["ai_providers.id"],
            name=op.f("fk_ai_task_assignments_provider_id_ai_providers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_ai_task_assignments_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_task_assignments")),
    )
    op.create_index(
        op.f("ix_ai_task_assignments_scope"),
        "ai_task_assignments",
        ["scope"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_task_assignments_task_type"),
        "ai_task_assignments",
        ["task_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_task_assignments_user_id"),
        "ai_task_assignments",
        ["user_id"],
        unique=False,
    )
    op.add_column(
        "users",
        sa.Column("is_admin", sa.Boolean(), server_default=sa.false(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_admin")
    op.drop_index(
        op.f("ix_ai_task_assignments_user_id"), table_name="ai_task_assignments"
    )
    op.drop_index(
        op.f("ix_ai_task_assignments_task_type"), table_name="ai_task_assignments"
    )
    op.drop_index(
        op.f("ix_ai_task_assignments_scope"), table_name="ai_task_assignments"
    )
    op.drop_table("ai_task_assignments")
    op.drop_index(op.f("ix_ai_models_provider_id"), table_name="ai_models")
    op.drop_table("ai_models")
    op.drop_index(op.f("ix_ai_providers_user_id"), table_name="ai_providers")
    op.drop_index(op.f("ix_ai_providers_scope"), table_name="ai_providers")
    op.drop_table("ai_providers")
    # ### end Alembic commands ###
