"""department application deadline

Revision ID: adb43f0e25b4
Revises: b93283357110
Create Date: 2026-08-28 10:13:19.908653
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "adb43f0e25b4"
down_revision: Union[str, None] = "b93283357110"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "departments", sa.Column("application_deadline", sa.Date(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("departments", "application_deadline")
    # ### end Alembic commands ###
