"""chat message timestamps

Revision ID: b93283357110
Revises: 046bb23aac42
Create Date: 2026-08-28 02:32:41.722607
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "b93283357110"
down_revision: Union[str, None] = "046bb23aac42"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_messages",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    op.add_column(
        "chat_messages",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_messages", "updated_at")
    op.drop_column("chat_messages", "created_at")
    # ### end Alembic commands ###
