#!/usr/bin/env bash
# worktree-env.sh — per-worktree isolation for concurrent agent sessions.
#
# Sourced by run-dev.sh / run-tests.sh / reset-test-db.sh / run-e2e.sh.
# If the current checkout is a linked git worktree AND a `.env.wt.local`
# file was generated by scripts/worktree.sh, all port and DATABASE_URL
# variables are overridden so the worktree talks to its own dev-db
# compose project (own containers, own ports, own volumes) instead of
# the primary checkout's. The primary checkout is unaffected (the file
# simply does not exist there).
#
# Precedence (highest first): real environment -> .env.wt.local -> .env.

_dc_wt_env_file() {
  local root
  root="$(git rev-parse --show-toplevel 2>/dev/null || true)"
  if [[ -n "$root" && -f "$root/.git" && -f "$root/.env.wt.local" ]]; then
    echo "$root/.env.wt.local"
  fi
}

# dc_wt_load — apply per-worktree overrides. Exports everything that is
# set in .env.wt.local without clobbering variables already set by the
# caller's environment (explicit env wins, mirroring pydantic-settings).
dc_wt_load() {
  local env_file
  env_file="$(_dc_wt_env_file)" || true
  [[ -z "$env_file" ]] && return 0
  local key value
  while IFS='=' read -r key value; do
    [[ "$key" =~ ^[A-Z_][A-Z0-9_]*$ ]] || continue
    [[ -n "${!key+x}" ]] && continue
    export "$key=$value"
  done < "$env_file"
}
