"""Seed catalog: job families, jobs with structured attributes, typed relations."""

from app.models.enums import EducationLevel, Environment, PhysicalActivity

FAMILIES: list[dict] = [
    {
        "key": "technology",
        "label": "Technology & IT",
        "parent": None,
        "description": "Software, data, hardware and digital infrastructure.",
    },
    {
        "key": "technology-software",
        "label": "Software Development",
        "parent": "technology",
    },
    {"key": "technology-data", "label": "Data & AI", "parent": "technology"},
    {
        "key": "technology-ops",
        "label": "IT Operations & Security",
        "parent": "technology",
    },
    {
        "key": "healthcare",
        "label": "Healthcare",
        "parent": None,
        "description": "Diagnosing, treating and caring for people.",
    },
    {"key": "healthcare-clinical", "label": "Clinical Care", "parent": "healthcare"},
    {
        "key": "healthcare-therapy",
        "label": "Therapy & Rehabilitation",
        "parent": "healthcare",
    },
    {"key": "healthcare-pharma", "label": "Pharmacy & Lab", "parent": "healthcare"},
    {
        "key": "education",
        "label": "Education & Training",
        "parent": None,
        "description": "Teaching, coaching and knowledge sharing.",
    },
    {
        "key": "engineering",
        "label": "Engineering & Trades",
        "parent": None,
        "description": "Designing, building and maintaining the physical world.",
    },
    {
        "key": "engineering-civil",
        "label": "Civil & Construction",
        "parent": "engineering",
    },
    {
        "key": "engineering-mechanical",
        "label": "Mechanical & Electrical",
        "parent": "engineering",
    },
    {
        "key": "business",
        "label": "Business & Finance",
        "parent": None,
        "description": "Markets, money, sales and organisations.",
    },
    {"key": "business-creative", "label": "Marketing & Media", "parent": "business"},
    {
        "key": "creative",
        "label": "Arts & Design",
        "parent": None,
        "description": "Visual, performing and media arts.",
    },
    {
        "key": "public-safety",
        "label": "Public Safety & Law",
        "parent": None,
        "description": "Protecting people and upholding the law.",
    },
    {
        "key": "science",
        "label": "Science & Environment",
        "parent": None,
        "description": "Research and understanding of nature.",
    },
    {
        "key": "agriculture",
        "label": "Agriculture & Animals",
        "parent": None,
        "description": "Farming, food production and animal care.",
    },
    {
        "key": "hospitality",
        "label": "Hospitality & Tourism",
        "parent": None,
        "description": "Food, travel and guest experiences.",
    },
]


def _ws(
    teamwork=3,
    environment=3,
    structure=3,
    pace=3,
    leadership=3,
    activity=PhysicalActivity.LIGHT,
):
    return {
        "teamwork": teamwork,
        "environment": environment,
        "structure": structure,
        "pace": pace,
        "leadership": leadership,
        "physical_activity": activity,
    }


def _edu(level: EducationLevel, fields=None):
    return {"level": level.value, "fields": fields or []}


def _salary(entry, median, senior):
    return {"currency": "USD", "entry": entry, "median": median, "senior": senior}


def _job(
    code,
    title,
    family,
    description,
    interests,
    skills,
    subjects,
    work_style,
    education,
    physical,
    salary,
    demand,
    environments,
    positives,
    negatives,
):
    return {
        "code": code,
        "title": title,
        "family": family,
        "description": description,
        "interests": interests,
        "skills": skills,
        "subjects": subjects,
        "work_style": work_style,
        "education": education,
        "physical": physical,
        "salary": salary,
        "demand": demand,
        "environments": environments,
        "positives": positives,
        "negatives": negatives,
    }


JOBS: list[dict] = [
    _job(
        "software-developer",
        "Software Developer",
        "technology-software",
        "Designs, writes and maintains applications and systems.",
        ["technology-software", "technology-ai", "technology-games"],
        ["programming", "problem-solving", "critical-thinking"],
        ["mathematics", "computer-science"],
        _ws(teamwork=4, structure=2),
        _edu(EducationLevel.BACHELOR, ["computer-science", "software-engineering"]),
        {"activity": PhysicalActivity.SEDENTARY, "requirements": []},
        _salary([35000, 55000], [60000, 95000], [100000, 160000]),
        {"outlook": "hot", "note": "Demand spans every industry.", "sources": {}},
        [Environment.OFFICE, Environment.REMOTE],
        [
            {"title": "High pay", "detail": "Among the strongest entry salaries."},
            {"title": "Remote-friendly", "detail": "Work from almost anywhere."},
            {"title": "Constant learning", "detail": "New tools keep the work fresh."},
        ],
        [
            {"title": "Screen fatigue", "detail": "Long hours at a desk."},
            {"title": "Always changing", "detail": "Skills can feel outdated quickly."},
        ],
    ),
    _job(
        "data-scientist",
        "Data Scientist",
        "technology-data",
        "Turns raw data into models and insights that guide decisions.",
        ["technology-data", "technology-ai", "science-mathematics"],
        ["data-analysis", "mathematics", "programming"],
        ["mathematics", "statistics"],
        _ws(structure=2, teamwork=3),
        _edu(
            EducationLevel.BACHELOR, ["statistics", "computer-science", "mathematics"]
        ),
        {"activity": PhysicalActivity.SEDENTARY, "requirements": []},
        _salary([40000, 60000], [70000, 110000], [110000, 170000]),
        {
            "outlook": "hot",
            "note": "AI adoption keeps expanding the field.",
            "sources": {},
        },
        [Environment.OFFICE, Environment.REMOTE],
        [
            {
                "title": "Intellectually rich",
                "detail": "Mix of math, code and domain puzzles.",
            },
            {"title": "Strong salaries", "detail": "Top of the tech pay scale."},
        ],
        [
            {"title": "Abstract work", "detail": "Results can feel far from people."},
            {
                "title": "Data cleaning grind",
                "detail": "Much time spent preparing data.",
            },
        ],
    ),
    _job(
        "ml-engineer",
        "Machine Learning Engineer",
        "technology-data",
        "Builds and deploys AI models into production systems.",
        ["technology-ai", "technology-software"],
        ["programming", "mathematics", "data-analysis"],
        ["mathematics", "computer-science"],
        _ws(teamwork=4, pace=4),
        _edu(EducationLevel.MASTER, ["computer-science", "ai"]),
        {"activity": PhysicalActivity.SEDENTARY, "requirements": []},
        _salary([50000, 75000], [85000, 130000], [130000, 200000]),
        {"outlook": "hot", "note": "Core role of the AI boom.", "sources": {}},
        [Environment.OFFICE, Environment.REMOTE],
        [
            {"title": "Frontier work", "detail": "Build with the latest AI tech."},
            {
                "title": "Very high pay",
                "detail": "One of the best-paid engineering roles.",
            },
        ],
        [
            {"title": "Steep learning curve", "detail": "Heavy math and engineering."},
            {"title": "On-call pressure", "detail": "Production models need care."},
        ],
    ),
    _job(
        "cybersecurity-analyst",
        "Cybersecurity Analyst",
        "technology-ops",
        "Protects networks and systems from attacks and intrusions.",
        ["technology-networks", "technology-software"],
        ["network-admin", "problem-solving", "attention-to-detail"],
        ["computer-science"],
        _ws(structure=3, pace=4),
        _edu(EducationLevel.BACHELOR, ["cybersecurity", "computer-science"]),
        {"activity": PhysicalActivity.SEDENTARY, "requirements": []},
        _salary([38000, 55000], [65000, 100000], [105000, 160000]),
        {
            "outlook": "hot",
            "note": "Attacks grow; defenders are scarce.",
            "sources": {},
        },
        [Environment.OFFICE, Environment.REMOTE],
        [
            {"title": "Purposeful", "detail": "Directly stops crime and damage."},
            {"title": "Job security", "detail": "Chronic talent shortage."},
        ],
        [
            {"title": "Alert fatigue", "detail": "Monitoring can be stressful."},
            {"title": "Incident nights", "detail": "Breaches do not wait for morning."},
        ],
    ),
    _job(
        "devops-engineer",
        "DevOps Engineer",
        "technology-ops",
        "Automates infrastructure and keeps online services running.",
        ["technology-software", "technology-networks"],
        ["programming", "network-admin", "problem-solving"],
        ["computer-science"],
        _ws(teamwork=4, pace=4),
        _edu(EducationLevel.BACHELOR, ["computer-science", "information-systems"]),
        {"activity": PhysicalActivity.SEDENTARY, "requirements": []},
        _salary([38000, 55000], [65000, 100000], [110000, 165000]),
        {"outlook": "growing", "note": "Cloud migration continues.", "sources": {}},
        [Environment.OFFICE, Environment.REMOTE],
        [
            {
                "title": "Automation wins",
                "detail": "You make machines do the boring parts.",
            },
            {"title": "High pay", "detail": "Scarce skill set."},
        ],
        [
            {"title": "On-call rotations", "detail": "Outages can wake you at night."},
            {"title": "Invisible work", "detail": "Good ops often goes unnoticed."},
        ],
    ),
    _job(
        "game-developer",
        "Game Developer",
        "technology-software",
        "Creates video games: gameplay, graphics and tools.",
        ["technology-games", "technology-software", "arts-visual"],
        ["programming", "problem-solving", "visual-design"],
        ["mathematics", "art"],
        _ws(teamwork=4, structure=2),
        _edu(EducationLevel.BACHELOR, ["computer-science", "game-design"]),
        {"activity": PhysicalActivity.SEDENTARY, "requirements": []},
        _salary([30000, 45000], [55000, 85000], [90000, 140000]),
        {
            "outlook": "stable",
            "note": "Competitive but passionate field.",
            "sources": {},
        },
        [Environment.OFFICE, Environment.REMOTE],
        [
            {
                "title": "Dream work for gamers",
                "detail": "You build worlds people love.",
            },
            {"title": "Creative + technical", "detail": "Art meets engineering."},
        ],
        [
            {"title": "Crunch culture", "detail": "Shipping can mean long nights."},
            {
                "title": "Lower pay than big tech",
                "detail": "Passion subsidises salaries.",
            },
        ],
    ),
    _job(
        "nurse",
        "Nurse (RN)",
        "healthcare-clinical",
        "Cares for patients, administers treatment and monitors recovery.",
        ["people-health", "people-helping", "science-biology"],
        ["empathy", "first-aid", "attention-to-detail"],
        ["biology", "chemistry"],
        _ws(teamwork=5, pace=4, activity=PhysicalActivity.ACTIVE),
        _edu(EducationLevel.BACHELOR, ["nursing"]),
        {
            "activity": PhysicalActivity.ACTIVE,
            "requirements": ["standing-long", "shift-work"],
        },
        _salary([40000, 55000], [60000, 85000], [85000, 120000]),
        {"outlook": "hot", "note": "Global nursing shortage.", "sources": {}},
        [Environment.CLINIC],
        [
            {"title": "Deep purpose", "detail": "You directly save and comfort lives."},
            {"title": "Jobs everywhere", "detail": "Needed in every town and country."},
            {
                "title": "Clear advancement",
                "detail": "Specialisations and leadership paths.",
            },
        ],
        [
            {"title": "Physically hard", "detail": "Long shifts on your feet."},
            {
                "title": "Emotional strain",
                "detail": "Loss and emergencies are part of it.",
            },
        ],
    ),
    _job(
        "physician",
        "Physician (Doctor)",
        "healthcare-clinical",
        "Diagnoses and treats illness; leads patient care.",
        ["people-health", "science-biology", "science-chemistry"],
        ["critical-thinking", "empathy", "attention-to-detail"],
        ["biology", "chemistry"],
        _ws(leadership=4, pace=4, activity=PhysicalActivity.LIGHT),
        _edu(EducationLevel.DOCTORATE, ["medicine"]),
        {"activity": PhysicalActivity.LIGHT, "requirements": ["long-education"]},
        _salary([55000, 75000], [120000, 220000], [200000, 400000]),
        {
            "outlook": "growing",
            "note": "Ageing populations need doctors.",
            "sources": {},
        },
        [Environment.CLINIC],
        [
            {
                "title": "Prestige and purpose",
                "detail": "Among the most trusted roles.",
            },
            {"title": "Excellent pay", "detail": "Top-tier lifetime earnings."},
        ],
        [
            {"title": "Very long training", "detail": "A decade or more of study."},
            {"title": "Heavy responsibility", "detail": "Life-and-death decisions."},
        ],
    ),
    _job(
        "paramedic",
        "Paramedic",
        "healthcare-clinical",
        "Provides emergency medical care on the scene and in transit.",
        ["people-health", "people-public-safety", "sports-fitness"],
        ["first-aid", "physical-stamina", "problem-solving"],
        ["biology"],
        _ws(pace=5, teamwork=4, activity=PhysicalActivity.INTENSE),
        _edu(EducationLevel.VOCATIONAL, ["emergency-medical-care"]),
        {
            "activity": PhysicalActivity.INTENSE,
            "requirements": ["heavy-lifting", "shift-work"],
        },
        _salary([28000, 40000], [40000, 60000], [60000, 85000]),
        {
            "outlook": "growing",
            "note": "Emergency services are expanding.",
            "sources": {},
        },
        [Environment.VEHICLE, Environment.OUTDOORS],
        [
            {"title": "Adrenaline and purpose", "detail": "Every shift matters."},
            {"title": "Fast entry", "detail": "Vocational path into healthcare."},
        ],
        [
            {"title": "Trauma exposure", "detail": "Sees accidents and loss."},
            {"title": "Weather and nights", "detail": "All conditions, all hours."},
        ],
    ),
    _job(
        "physiotherapist",
        "Physiotherapist",
        "healthcare-therapy",
        "Restores movement and manages pain through exercise and therapy.",
        ["people-health", "sports-fitness", "science-biology"],
        ["empathy", "teaching", "physical-stamina"],
        ["biology", "sports-science"],
        _ws(teamwork=3, activity=PhysicalActivity.MODERATE),
        _edu(EducationLevel.MASTER, ["physiotherapy"]),
        {"activity": PhysicalActivity.MODERATE, "requirements": ["hands-on"]},
        _salary([35000, 50000], [55000, 80000], [80000, 110000]),
        {
            "outlook": "growing",
            "note": "Sports and ageing drive demand.",
            "sources": {},
        },
        [Environment.CLINIC],
        [
            {"title": "Visible progress", "detail": "Patients recover week by week."},
            {"title": "Active workplace", "detail": "Not a desk job."},
        ],
        [
            {"title": "Slow cases", "detail": "Some patients plateau."},
            {"title": "Master's required", "detail": "Long study path."},
        ],
    ),
    _job(
        "psychologist",
        "Psychologist",
        "healthcare-therapy",
        "Studies behaviour and helps people with mental health.",
        ["people-helping", "science-biology", "people-teaching"],
        ["empathy", "critical-thinking", "writing"],
        ["psychology", "biology"],
        _ws(structure=2, teamwork=2),
        _edu(EducationLevel.MASTER, ["psychology"]),
        {"activity": PhysicalActivity.SEDENTARY, "requirements": []},
        _salary([35000, 50000], [60000, 90000], [90000, 130000]),
        {"outlook": "growing", "note": "Mental health awareness rises.", "sources": {}},
        [Environment.CLINIC, Environment.OFFICE],
        [
            {"title": "Meaningful impact", "detail": "Changes the course of lives."},
            {
                "title": "Flexible practice",
                "detail": "Private clinic or organisations.",
            },
        ],
        [
            {"title": "Emotional load", "detail": "Carries others' trauma."},
            {"title": "Long qualification", "detail": "Licensing takes years."},
        ],
    ),
    _job(
        "pharmacist",
        "Pharmacist",
        "healthcare-pharma",
        "Dispenses medicines and advises on their safe use.",
        ["science-chemistry", "people-health"],
        ["attention-to-detail", "memory-accuracy", "empathy"],
        ["chemistry", "biology"],
        _ws(structure=4),
        _edu(EducationLevel.MASTER, ["pharmacy"]),
        {"activity": PhysicalActivity.LIGHT, "requirements": []},
        _salary([45000, 60000], [75000, 105000], [105000, 140000]),
        {"outlook": "stable", "note": "Steady healthcare staple.", "sources": {}},
        [Environment.CLINIC],
        [
            {"title": "Stable and respected", "detail": "Clear licensed profession."},
            {"title": "Chemistry in action", "detail": "Science you use daily."},
        ],
        [
            {"title": "Repetitive", "detail": "Many similar prescriptions."},
            {"title": "Long degree", "detail": "Five-plus years of study."},
        ],
    ),
    _job(
        "medical-lab-technician",
        "Medical Laboratory Technician",
        "healthcare-pharma",
        "Runs tests on samples that guide diagnosis.",
        ["science-biology", "science-chemistry"],
        ["lab-techniques", "attention-to-detail"],
        ["biology", "chemistry"],
        _ws(structure=4, teamwork=2),
        _edu(EducationLevel.VOCATIONAL, ["biomedical-science"]),
        {"activity": PhysicalActivity.LIGHT, "requirements": []},
        _salary([28000, 40000], [45000, 65000], [65000, 90000]),
        {"outlook": "stable", "note": "Backbone of diagnostics.", "sources": {}},
        [Environment.LAB],
        [
            {
                "title": "Behind-the-scenes hero",
                "detail": "Your results drive treatment.",
            },
            {"title": "Ordered work", "detail": "Clear procedures and structure."},
        ],
        [
            {"title": "Little patient contact", "detail": "Samples, not people."},
            {"title": "Repetitive testing", "detail": "Routine can dominate."},
        ],
    ),
    _job(
        "teacher",
        "School Teacher",
        "education",
        "Teaches and mentors students in a subject area.",
        ["people-teaching", "arts-writing", "society-history"],
        ["teaching", "public-speaking", "empathy"],
        ["any"],
        _ws(teamwork=3, structure=3, activity=PhysicalActivity.MODERATE),
        _edu(EducationLevel.BACHELOR, ["education", "subject-field"]),
        {"activity": PhysicalActivity.MODERATE, "requirements": ["standing-long"]},
        _salary([28000, 40000], [42000, 65000], [65000, 95000]),
        {"outlook": "stable", "note": "Persistent shortages in STEM.", "sources": {}},
        [Environment.CLASSROOM],
        [
            {"title": "Shape young minds", "detail": "Rare daily impact on others."},
            {"title": "Holidays", "detail": "Long breaks each year."},
        ],
        [
            {"title": "Heavy marking", "detail": "Evenings spent grading."},
            {"title": "Classroom stress", "detail": "Managing 30 teenagers is hard."},
        ],
    ),
    _job(
        "special-education-teacher",
        "Special Education Teacher",
        "education",
        "Adapts teaching for students with special needs.",
        ["people-teaching", "people-helping"],
        ["empathy", "teaching", "problem-solving"],
        ["psychology"],
        _ws(teamwork=4, activity=PhysicalActivity.MODERATE),
        _edu(EducationLevel.BACHELOR, ["special-education"]),
        {"activity": PhysicalActivity.MODERATE, "requirements": []},
        _salary([30000, 42000], [45000, 68000], [68000, 95000]),
        {"outlook": "growing", "note": "High-need specialisation.", "sources": {}},
        [Environment.CLASSROOM],
        [
            {
                "title": "Profound difference",
                "detail": "Progress changes whole families.",
            },
            {"title": "Small groups", "detail": "Closer student relationships."},
        ],
        [
            {
                "title": "Emotionally demanding",
                "detail": "Slow progress can frustrate.",
            },
            {"title": "Paperwork", "detail": "Plans and reviews per student."},
        ],
    ),
    _job(
        "civil-engineer",
        "Civil Engineer",
        "engineering-civil",
        "Designs and oversees bridges, roads and buildings.",
        ["hands-building", "science-physics", "technology-software"],
        ["engineering-design", "mathematics", "problem-solving"],
        ["mathematics", "physics"],
        _ws(teamwork=4, leadership=3),
        _edu(EducationLevel.BACHELOR, ["civil-engineering"]),
        {"activity": PhysicalActivity.MODERATE, "requirements": ["site-visits"]},
        _salary([35000, 50000], [60000, 90000], [90000, 130000]),
        {
            "outlook": "stable",
            "note": "Infrastructure spending persists.",
            "sources": {},
        },
        [Environment.OFFICE, Environment.OUTDOORS],
        [
            {"title": "Monuments to your work", "detail": "Structures outlive you."},
            {"title": "Mix of office and site", "detail": "Variety of settings."},
        ],
        [
            {"title": "Liability pressure", "detail": "Safety rests on your calcs."},
            {"title": "Site weather", "detail": "Outdoor inspections in winter."},
        ],
    ),
    _job(
        "electrician",
        "Electrician",
        "engineering-mechanical",
        "Installs and repairs electrical systems.",
        ["hands-electricity", "hands-building"],
        ["dexterity", "problem-solving", "attention-to-detail"],
        ["physics"],
        _ws(structure=2, activity=PhysicalActivity.MODERATE),
        _edu(EducationLevel.VOCATIONAL, ["electrical-installation"]),
        {
            "activity": PhysicalActivity.MODERATE,
            "requirements": ["physical-labor", "heights"],
        },
        _salary([28000, 40000], [45000, 70000], [70000, 100000]),
        {
            "outlook": "growing",
            "note": "Electrification and renewables boom.",
            "sources": {},
        },
        [Environment.WORKSHOP, Environment.OUTDOORS],
        [
            {"title": "Earn while learning", "detail": "Paid apprenticeships."},
            {"title": "Evergreen trade", "detail": "Every building needs power."},
        ],
        [
            {"title": "Physical strain", "detail": "Ladders, crawlspaces, tools."},
            {"title": "Shock risk", "detail": "Safety discipline is vital."},
        ],
    ),
    _job(
        "mechanical-engineer",
        "Mechanical Engineer",
        "engineering-mechanical",
        "Designs machines, engines and mechanical systems.",
        ["hands-machines", "science-physics", "technology-robots"],
        ["engineering-design", "mathematics", "problem-solving"],
        ["mathematics", "physics"],
        _ws(teamwork=4),
        _edu(EducationLevel.BACHELOR, ["mechanical-engineering"]),
        {"activity": PhysicalActivity.LIGHT, "requirements": []},
        _salary([35000, 50000], [60000, 90000], [95000, 135000]),
        {"outlook": "stable", "note": "Broad industrial applicability.", "sources": {}},
        [Environment.OFFICE, Environment.WORKSHOP],
        [
            {"title": "Tangible products", "detail": "You can hold what you designed."},
            {"title": "Versatile degree", "detail": "Doors in many industries."},
        ],
        [
            {"title": "Documentation", "detail": "Specs and compliance paperwork."},
            {"title": "Slow iterations", "detail": "Prototypes take time."},
        ],
    ),
    _job(
        "robotics-technician",
        "Robotics Technician",
        "engineering-mechanical",
        "Builds, programs and maintains industrial robots.",
        ["technology-robots", "hands-machines", "technology-software"],
        ["electronics", "programming", "mechanical-repair"],
        ["physics", "computer-science"],
        _ws(teamwork=3, activity=PhysicalActivity.MODERATE),
        _edu(EducationLevel.VOCATIONAL, ["mechatronics"]),
        {"activity": PhysicalActivity.MODERATE, "requirements": ["physical-labor"]},
        _salary([30000, 45000], [50000, 75000], [75000, 105000]),
        {"outlook": "hot", "note": "Factory automation accelerates.", "sources": {}},
        [Environment.WORKSHOP],
        [
            {"title": "Future-facing", "detail": "Robots are the growth story."},
            {"title": "Hands + code", "detail": "Perfect blend of interests."},
        ],
        [
            {"title": "Factory hours", "detail": "Production schedules rule."},
            {"title": "Troubleshooting pressure", "detail": "Down robots cost money."},
        ],
    ),
    _job(
        "architect",
        "Architect",
        "engineering-civil",
        "Designs buildings that are safe, useful and beautiful.",
        ["arts-design", "hands-building", "arts-visual"],
        ["engineering-design", "visual-design", "critical-thinking"],
        ["art", "mathematics", "physics"],
        _ws(structure=2, teamwork=4),
        _edu(EducationLevel.MASTER, ["architecture"]),
        {"activity": PhysicalActivity.LIGHT, "requirements": []},
        _salary([32000, 45000], [55000, 85000], [85000, 130000]),
        {"outlook": "stable", "note": "Tied to construction cycles.", "sources": {}},
        [Environment.STUDIO],
        [
            {"title": "Art meets engineering", "detail": "Creative and technical."},
            {"title": "Lasting legacy", "detail": "Buildings define skylines."},
        ],
        [
            {"title": "Long qualification", "detail": "School plus internship years."},
            {"title": "Client compromises", "detail": "Vision meets budget."},
        ],
    ),
    _job(
        "accountant",
        "Accountant",
        "business",
        "Keeps financial records accurate and prepares reports.",
        ["business-finance", "technology-data"],
        ["attention-to-detail", "organization", "data-analysis"],
        ["mathematics", "economics"],
        _ws(structure=5, teamwork=2),
        _edu(EducationLevel.BACHELOR, ["accounting", "finance"]),
        {"activity": PhysicalActivity.SEDENTARY, "requirements": []},
        _salary([32000, 45000], [50000, 75000], [75000, 120000]),
        {"outlook": "stable", "note": "Every company needs one.", "sources": {}},
        [Environment.OFFICE, Environment.REMOTE],
        [
            {"title": "Rock-solid demand", "detail": "Recession-resistant profession."},
            {"title": "Clear career ladder", "detail": "Certificates map to raises."},
        ],
        [
            {"title": "Deadline seasons", "detail": "Quarter-ends get intense."},
            {"title": "Perceived as boring", "detail": "Structure over novelty."},
        ],
    ),
    _job(
        "financial-analyst",
        "Financial Analyst",
        "business",
        "Evaluates investments and guides financial decisions.",
        ["business-finance", "technology-data", "business-entrepreneurship"],
        ["data-analysis", "critical-thinking", "negotiation"],
        ["mathematics", "economics"],
        _ws(pace=4, teamwork=3),
        _edu(EducationLevel.BACHELOR, ["finance", "economics"]),
        {"activity": PhysicalActivity.SEDENTARY, "requirements": []},
        _salary([40000, 60000], [65000, 100000], [100000, 180000]),
        {"outlook": "stable", "note": "Capital markets keep humming.", "sources": {}},
        [Environment.OFFICE],
        [
            {"title": "High earnings", "detail": "Bonuses on top of salary."},
            {"title": "Markets every day", "detail": "Follow the real economy."},
        ],
        [
            {"title": "Market stress", "detail": "Downturns mean pressure."},
            {"title": "Long hours in banking", "detail": "Culture varies by firm."},
        ],
    ),
    _job(
        "marketing-specialist",
        "Marketing Specialist",
        "business-creative",
        "Promotes products through campaigns, content and analysis.",
        ["business-marketing", "arts-writing", "technology-data"],
        ["writing", "visual-design", "data-analysis"],
        ["economics", "media-studies"],
        _ws(teamwork=4, structure=2),
        _edu(EducationLevel.BACHELOR, ["marketing", "communications"]),
        {"activity": PhysicalActivity.SEDENTARY, "requirements": []},
        _salary([28000, 42000], [45000, 70000], [70000, 110000]),
        {"outlook": "growing", "note": "Digital channels multiply.", "sources": {}},
        [Environment.OFFICE, Environment.REMOTE],
        [
            {"title": "Creative + analytic", "detail": "Left and right brain."},
            {"title": "Trendy industry", "detail": "Fast-moving and social."},
        ],
        [
            {"title": "Metric pressure", "detail": "Campaigns are judged by numbers."},
            {"title": "Trend treadmill", "detail": "What worked yesterday fades."},
        ],
    ),
    _job(
        "sales-representative",
        "Sales Representative",
        "business",
        "Sells products and builds client relationships.",
        ["business-sales", "business-entrepreneurship"],
        ["negotiation", "empathy", "public-speaking"],
        ["any"],
        _ws(pace=4, structure=2, teamwork=3),
        _edu(EducationLevel.HIGH_SCHOOL, []),
        {"activity": PhysicalActivity.LIGHT, "requirements": ["travel"]},
        _salary([25000, 40000], [45000, 80000], [80000, 150000]),
        {
            "outlook": "stable",
            "note": "Always needed; commission-heavy.",
            "sources": {},
        },
        [Environment.OFFICE, Environment.VEHICLE],
        [
            {"title": "Uncapped earnings", "detail": "Great sellers print money."},
            {"title": "Low entry bar", "detail": "Skill matters more than degree."},
        ],
        [
            {"title": "Rejection daily", "detail": "Thick skin required."},
            {"title": "Target pressure", "detail": "Quotas follow you home."},
        ],
    ),
    _job(
        "graphic-designer",
        "Graphic Designer",
        "creative",
        "Creates visual identities, layouts and campaign art.",
        ["arts-design", "arts-visual", "technology-software"],
        ["visual-design", "storytelling", "attention-to-detail"],
        ["art"],
        _ws(structure=2, teamwork=3),
        _edu(EducationLevel.VOCATIONAL, ["graphic-design"]),
        {"activity": PhysicalActivity.SEDENTARY, "requirements": []},
        _salary([25000, 38000], [40000, 65000], [65000, 95000]),
        {"outlook": "stable", "note": "AI tools reshape the craft.", "sources": {}},
        [Environment.STUDIO, Environment.REMOTE],
        [
            {"title": "Creative daily", "detail": "Your eye is the product."},
            {"title": "Freelance-friendly", "detail": "Easy independent path."},
        ],
        [
            {"title": "Subjective feedback", "detail": "Endless revisions."},
            {"title": "AI competition", "detail": "Commoditised basics."},
        ],
    ),
    _job(
        "ux-designer",
        "UX Designer",
        "creative",
        "Designs how apps and websites feel and flow for users.",
        ["arts-design", "technology-software", "people-helping"],
        ["visual-design", "empathy", "problem-solving"],
        ["psychology", "art"],
        _ws(teamwork=4, structure=3),
        _edu(EducationLevel.BACHELOR, ["interaction-design", "psychology"]),
        {"activity": PhysicalActivity.SEDENTARY, "requirements": []},
        _salary([32000, 48000], [55000, 85000], [85000, 125000]),
        {
            "outlook": "growing",
            "note": "Digital products need human-centred design.",
            "sources": {},
        },
        [Environment.OFFICE, Environment.REMOTE],
        [
            {"title": "Psychology + design", "detail": "Understand people, then draw."},
            {"title": "Strong tech salaries", "detail": "Design is valued in tech."},
        ],
        [
            {"title": "Stakeholder tug-of-war", "detail": "Opinions clash on taste."},
            {"title": "Research grind", "detail": "User testing takes patience."},
        ],
    ),
    _job(
        "journalist",
        "Journalist",
        "business-creative",
        "Researches and reports news stories for the public.",
        ["society-media", "arts-writing", "society-politics"],
        ["writing", "critical-thinking", "public-speaking"],
        ["history", "literature"],
        _ws(pace=4, structure=2, teamwork=2),
        _edu(EducationLevel.BACHELOR, ["journalism", "communications"]),
        {"activity": PhysicalActivity.LIGHT, "requirements": ["deadlines"]},
        _salary([24000, 35000], [40000, 65000], [65000, 100000]),
        {
            "outlook": "declining",
            "note": "Traditional media shrinking; niches grow.",
            "sources": {},
        },
        [Environment.OFFICE, Environment.OUTDOORS],
        [
            {"title": "Truth-telling", "detail": "Democracy's front line."},
            {"title": "Every day differs", "detail": "New stories constantly."},
        ],
        [
            {"title": "Shrinking jobs", "detail": "Newsroom cuts continue."},
            {"title": "Deadline treadmill", "detail": "Constant time pressure."},
        ],
    ),
    _job(
        "police-officer",
        "Police Officer",
        "public-safety",
        "Enforces laws and protects the public.",
        ["people-public-safety", "sports-fitness", "people-law-justice"],
        ["physical-stamina", "conflict-resolution", "first-aid"],
        ["any"],
        _ws(teamwork=4, pace=4, activity=PhysicalActivity.ACTIVE),
        _edu(EducationLevel.VOCATIONAL, ["police-academy"]),
        {
            "activity": PhysicalActivity.ACTIVE,
            "requirements": ["physical-fitness", "shift-work"],
        },
        _salary([30000, 42000], [45000, 70000], [70000, 95000]),
        {"outlook": "stable", "note": "Constant public need.", "sources": {}},
        [Environment.OUTDOORS, Environment.VEHICLE],
        [
            {"title": "Serve the community", "detail": "Direct protection of people."},
            {"title": "Pension and stability", "detail": "Strong public benefits."},
        ],
        [
            {"title": "Dangerous", "detail": "Confrontation is possible."},
            {"title": "Shift work", "detail": "Nights, weekends, holidays."},
        ],
    ),
    _job(
        "firefighter",
        "Firefighter",
        "public-safety",
        "Fights fires and rescues people from emergencies.",
        ["people-public-safety", "sports-fitness", "people-helping"],
        ["physical-stamina", "first-aid", "teamwork"],
        ["any"],
        _ws(teamwork=5, pace=5, activity=PhysicalActivity.INTENSE),
        _edu(EducationLevel.VOCATIONAL, ["fire-science"]),
        {
            "activity": PhysicalActivity.INTENSE,
            "requirements": ["heavy-lifting", "physical-fitness", "shift-work"],
        },
        _salary([28000, 40000], [45000, 65000], [65000, 90000]),
        {"outlook": "stable", "note": "Municipal staple.", "sources": {}},
        [Environment.OUTDOORS],
        [
            {"title": "Elite teamwork", "detail": "Crew bonds run deep."},
            {"title": "Heroic work", "detail": "Rescue people at their worst."},
        ],
        [
            {"title": "Extreme physicality", "detail": "Heavy gear in heat."},
            {"title": "Trauma risk", "detail": "Rescue can end in loss."},
        ],
    ),
    _job(
        "lawyer",
        "Lawyer",
        "public-safety",
        "Advises and represents clients on legal matters.",
        ["people-law-justice", "arts-writing", "society-politics"],
        ["critical-thinking", "negotiation", "public-speaking"],
        ["history", "literature"],
        _ws(structure=2, pace=4, teamwork=2),
        _edu(EducationLevel.MASTER, ["law"]),
        {"activity": PhysicalActivity.SEDENTARY, "requirements": []},
        _salary([40000, 60000], [70000, 120000], [120000, 250000]),
        {"outlook": "stable", "note": "Legal needs never vanish.", "sources": {}},
        [Environment.OFFICE],
        [
            {"title": "Prestige and pay", "detail": "Top-tier profession."},
            {"title": "Argument craft", "detail": "Logic as a sport."},
        ],
        [
            {"title": "Billable-hour grind", "detail": "Long documented hours."},
            {"title": "Expensive training", "detail": "Law school costs."},
        ],
    ),
    _job(
        "social-worker",
        "Social Worker",
        "public-safety",
        "Supports families and individuals through hard times.",
        ["people-helping", "society-politics", "people-teaching"],
        ["empathy", "conflict-resolution", "organization"],
        ["psychology", "sociology"],
        _ws(teamwork=4, activity=PhysicalActivity.MODERATE),
        _edu(EducationLevel.BACHELOR, ["social-work"]),
        {"activity": PhysicalActivity.MODERATE, "requirements": ["field-visits"]},
        _salary([28000, 38000], [42000, 60000], [60000, 85000]),
        {"outlook": "growing", "note": "Social services expanding.", "sources": {}},
        [Environment.OFFICE, Environment.OUTDOORS],
        [
            {"title": "Lifeline role", "detail": "Help where it's needed most."},
            {"title": "Variety of cases", "detail": "No two families alike."},
        ],
        [
            {"title": "Heavy caseloads", "detail": "Systemic underfunding."},
            {"title": "Hard stories", "detail": "Abuse and poverty daily."},
        ],
    ),
    _job(
        "environmental-scientist",
        "Environmental Scientist",
        "science",
        "Studies ecosystems and pollution to protect nature.",
        ["society-environment", "science-earth", "science-biology"],
        ["data-analysis", "lab-techniques", "critical-thinking"],
        ["biology", "chemistry", "geography"],
        _ws(structure=3, teamwork=3, activity=PhysicalActivity.MODERATE),
        _edu(EducationLevel.BACHELOR, ["environmental-science"]),
        {"activity": PhysicalActivity.MODERATE, "requirements": ["fieldwork"]},
        _salary([30000, 42000], [50000, 75000], [75000, 105000]),
        {"outlook": "growing", "note": "Climate agenda fuels roles.", "sources": {}},
        [Environment.LAB, Environment.OUTDOORS],
        [
            {"title": "Mission-driven", "detail": "Work for the planet."},
            {"title": "Lab + field mix", "detail": "Indoor and outdoor balance."},
        ],
        [
            {"title": "Policy frustration", "detail": "Science vs politics."},
            {"title": "Grant cycles", "detail": "Funding insecurity."},
        ],
    ),
    _job(
        "biologist",
        "Biologist (Research)",
        "science",
        "Researches living systems, from cells to ecosystems.",
        ["science-biology", "nature-animals"],
        ["lab-techniques", "critical-thinking", "data-analysis"],
        ["biology", "chemistry"],
        _ws(structure=3, teamwork=2),
        _edu(EducationLevel.MASTER, ["biology"]),
        {"activity": PhysicalActivity.LIGHT, "requirements": []},
        _salary([28000, 40000], [45000, 70000], [70000, 110000]),
        {
            "outlook": "stable",
            "note": "Biotech growth offsets academia.",
            "sources": {},
        },
        [Environment.LAB, Environment.OUTDOORS],
        [
            {"title": "Discover the unknown", "detail": "Real research frontiers."},
            {"title": "Curiosity-driven", "detail": "Follow fascinating questions."},
        ],
        [
            {"title": "Modest academic pay", "detail": "PhD path is long."},
            {"title": "Repetition", "detail": "Experiments fail often."},
        ],
    ),
    _job(
        "chemist",
        "Chemist",
        "science",
        "Analyses substances and develops new materials.",
        ["science-chemistry", "technology-data"],
        ["lab-techniques", "attention-to-detail", "critical-thinking"],
        ["chemistry", "mathematics"],
        _ws(structure=4, teamwork=3),
        _edu(EducationLevel.BACHELOR, ["chemistry"]),
        {"activity": PhysicalActivity.LIGHT, "requirements": []},
        _salary([30000, 42000], [50000, 75000], [75000, 110000]),
        {"outlook": "stable", "note": "Industry, pharma and materials.", "sources": {}},
        [Environment.LAB],
        [
            {"title": "Molecular detective", "detail": "Understand matter itself."},
            {"title": "Industrial relevance", "detail": "Products need chemists."},
        ],
        [
            {"title": "Safety protocols", "detail": "Hazardous materials."},
            {"title": "Precise routines", "detail": "Little improvisation."},
        ],
    ),
    _job(
        "wildlife-biologist",
        "Wildlife Biologist",
        "science",
        "Studies animals in their natural habitats.",
        ["nature-animals", "science-biology", "sports-outdoors"],
        ["data-analysis", "physical-stamina", "critical-thinking"],
        ["biology", "geography"],
        _ws(teamwork=2, structure=2, activity=PhysicalActivity.ACTIVE),
        _edu(EducationLevel.MASTER, ["zoology", "ecology"]),
        {
            "activity": PhysicalActivity.ACTIVE,
            "requirements": ["fieldwork", "outdoor-conditions"],
        },
        _salary([26000, 38000], [42000, 65000], [65000, 95000]),
        {"outlook": "stable", "note": "Conservation funding dependent.", "sources": {}},
        [Environment.OUTDOORS, Environment.LAB],
        [
            {"title": "Live with nature", "detail": "Fieldwork in wild places."},
            {"title": "Conservation impact", "detail": "Protect species directly."},
        ],
        [
            {"title": "Modest pay", "detail": "Passion-driven field."},
            {"title": "Remote postings", "detail": "Far from cities."},
        ],
    ),
    _job(
        "veterinarian",
        "Veterinarian",
        "agriculture",
        "Diagnoses and treats animals.",
        ["nature-animals-care", "science-biology", "people-health"],
        ["critical-thinking", "empathy", "dexterity"],
        ["biology", "chemistry"],
        _ws(pace=4, teamwork=3, activity=PhysicalActivity.MODERATE),
        _edu(EducationLevel.DOCTORATE, ["veterinary-medicine"]),
        {"activity": PhysicalActivity.MODERATE, "requirements": ["animal-handling"]},
        _salary([45000, 60000], [75000, 110000], [110000, 160000]),
        {"outlook": "growing", "note": "Pet care spending booms.", "sources": {}},
        [Environment.CLINIC],
        [
            {"title": "Heal animals", "detail": "Patients everyone loves."},
            {"title": "Diverse cases", "detail": "From hamsters to horses."},
        ],
        [
            {"title": "Long training", "detail": "Very competitive admission."},
            {"title": "Emotional euthanasia", "detail": "Hard moments weekly."},
        ],
    ),
    _job(
        "veterinary-technician",
        "Veterinary Technician",
        "agriculture",
        "Assists vets with animal care and procedures.",
        ["nature-animals-care", "people-health"],
        ["empathy", "dexterity", "attention-to-detail"],
        ["biology"],
        _ws(pace=4, teamwork=4, activity=PhysicalActivity.MODERATE),
        _edu(EducationLevel.VOCATIONAL, ["veterinary-technology"]),
        {"activity": PhysicalActivity.MODERATE, "requirements": ["animal-handling"]},
        _salary([24000, 34000], [35000, 52000], [52000, 70000]),
        {"outlook": "growing", "note": "Fast entry into animal care.", "sources": {}},
        [Environment.CLINIC],
        [
            {"title": "Animals all day", "detail": "Direct care work."},
            {"title": "Two-year entry", "detail": "Quick qualification."},
        ],
        [
            {"title": "Bites and scratches", "detail": "Patients bite."},
            {"title": "Modest pay", "detail": "Above-minimum wage only."},
        ],
    ),
    _job(
        "agronomist",
        "Agronomist",
        "agriculture",
        "Improves crop production and soil health.",
        ["nature-plants", "science-biology", "society-environment"],
        ["data-analysis", "problem-solving", "lab-techniques"],
        ["biology", "chemistry"],
        _ws(structure=3, activity=PhysicalActivity.MODERATE),
        _edu(EducationLevel.BACHELOR, ["agronomy"]),
        {"activity": PhysicalActivity.MODERATE, "requirements": ["fieldwork"]},
        _salary([28000, 40000], [45000, 68000], [68000, 95000]),
        {
            "outlook": "growing",
            "note": "Food security + sustainability.",
            "sources": {},
        },
        [Environment.OUTDOORS, Environment.LAB],
        [
            {"title": "Feed the world", "detail": "Fundamental human mission."},
            {"title": "Science outdoors", "detail": "Fields are your lab."},
        ],
        [
            {"title": "Seasonal pressure", "detail": "Harvest waits for no one."},
            {"title": "Rural locations", "detail": "Often away from cities."},
        ],
    ),
    _job(
        "farmer",
        "Farmer",
        "agriculture",
        "Grows crops or raises livestock for food.",
        ["nature-plants", "hands-machines", "business-entrepreneurship"],
        ["physical-stamina", "organization", "mechanical-repair"],
        ["biology"],
        _ws(structure=3, leadership=4, activity=PhysicalActivity.INTENSE),
        _edu(EducationLevel.NO_FORMAL, []),
        {
            "activity": PhysicalActivity.INTENSE,
            "requirements": ["physical-labor", "early-mornings"],
        },
        _salary([20000, 35000], [35000, 60000], [60000, 120000]),
        {
            "outlook": "stable",
            "note": "Consolidation; organic niches grow.",
            "sources": {},
        },
        [Environment.OUTDOORS],
        [
            {"title": "Be your own boss", "detail": "Independent livelihood."},
            {"title": "Tangible results", "detail": "Harvest you can touch."},
        ],
        [
            {"title": "Weather gamble", "detail": "Nature can ruin a year."},
            {"title": "No days off", "detail": "Animals eat daily."},
        ],
    ),
    _job(
        "chef",
        "Chef",
        "hospitality",
        "Leads kitchen teams and creates dishes.",
        ["hands-cooking", "business-entrepreneurship", "arts-design"],
        ["cooking", "leadership", "problem-solving"],
        ["any"],
        _ws(pace=5, teamwork=5, activity=PhysicalActivity.ACTIVE),
        _edu(EducationLevel.VOCATIONAL, ["culinary-arts"]),
        {
            "activity": PhysicalActivity.ACTIVE,
            "requirements": ["standing-long", "hot-environment"],
        },
        _salary([24000, 35000], [40000, 65000], [65000, 120000]),
        {"outlook": "stable", "note": "Restaurants always need talent.", "sources": {}},
        [Environment.KITCHEN],
        [
            {"title": "Creative craft", "detail": "Food as art."},
            {"title": "Fast growth", "detail": "Skill beats credentials."},
        ],
        [
            {"title": "Brutal hours", "detail": "Evenings, weekends, holidays."},
            {"title": "High heat and stress", "detail": "Service rush is intense."},
        ],
    ),
    _job(
        "hotel-manager",
        "Hotel Manager",
        "hospitality",
        "Runs hotel operations and guest experience.",
        ["business-management", "people-helping", "society-languages"],
        ["leadership", "customer-service", "organization"],
        ["economics"],
        _ws(leadership=5, pace=4, teamwork=4),
        _edu(EducationLevel.BACHELOR, ["hospitality-management"]),
        {"activity": PhysicalActivity.MODERATE, "requirements": []},
        _salary([30000, 45000], [50000, 80000], [80000, 120000]),
        {"outlook": "growing", "note": "Travel keeps rebounding.", "sources": {}},
        [Environment.OFFICE],
        [
            {"title": "People + business", "detail": "Lead teams, host guests."},
            {"title": "Global industry", "detail": "Work anywhere."},
        ],
        [
            {"title": "Always on", "detail": "Guest issues at 2am."},
            {"title": "Weekend work", "detail": "Peak times are yours."},
        ],
    ),
    _job(
        "logistics-coordinator",
        "Logistics Coordinator",
        "business",
        "Moves goods efficiently through supply chains.",
        ["business-logistics", "technology-data"],
        ["organization", "problem-solving", "negotiation"],
        ["economics", "geography"],
        _ws(structure=4, pace=4, teamwork=3),
        _edu(EducationLevel.BACHELOR, ["logistics", "business"]),
        {"activity": PhysicalActivity.LIGHT, "requirements": []},
        _salary([28000, 40000], [45000, 68000], [68000, 95000]),
        {"outlook": "growing", "note": "E-commerce logistics boom.", "sources": {}},
        [Environment.OFFICE],
        [
            {"title": "Global puzzle", "detail": "Orchestrate world trade."},
            {"title": "E-commerce tailwind", "detail": "Sector keeps growing."},
        ],
        [
            {"title": "Firefighting", "detail": "Delays cascade daily."},
            {"title": "Time-zone calls", "detail": "Early or late meetings."},
        ],
    ),
    _job(
        "pilot",
        "Pilot (Commercial)",
        "hospitality",
        "Flies aircraft for airlines or cargo.",
        ["hands-driving", "science-physics", "sports-outdoors"],
        ["driving", "attention-to-detail", "problem-solving"],
        ["physics", "mathematics"],
        _ws(structure=4, teamwork=3, activity=PhysicalActivity.MODERATE),
        _edu(EducationLevel.VOCATIONAL, ["aviation"]),
        {
            "activity": PhysicalActivity.MODERATE,
            "requirements": ["medical-certificate", "shift-work"],
        },
        _salary([30000, 50000], [70000, 120000], [120000, 200000]),
        {"outlook": "growing", "note": "Pilot shortage projected.", "sources": {}},
        [Environment.VEHICLE],
        [
            {"title": "Views and travel", "detail": "Office above the clouds."},
            {"title": "Elite pay", "detail": "Senior pilots earn large."},
        ],
        [
            {"title": "Expensive licence", "detail": "Training costs a fortune."},
            {"title": "Circadian grind", "detail": "Jet lag and red-eyes."},
        ],
    ),
    _job(
        "electric-vehicle-technician",
        "EV Technician",
        "engineering-mechanical",
        "Services and repairs electric vehicles.",
        ["hands-electricity", "hands-machines", "technology-hardware"],
        ["electronics", "mechanical-repair", "problem-solving"],
        ["physics"],
        _ws(structure=3, teamwork=2, activity=PhysicalActivity.MODERATE),
        _edu(EducationLevel.VOCATIONAL, ["automotive-technology"]),
        {"activity": PhysicalActivity.MODERATE, "requirements": ["physical-labor"]},
        _salary([28000, 40000], [48000, 70000], [70000, 95000]),
        {"outlook": "hot", "note": "EV fleet grows yearly.", "sources": {}},
        [Environment.WORKSHOP],
        [
            {"title": "Ride the EV wave", "detail": "Skills of the future."},
            {"title": "Trade security", "detail": "Hard to offshore."},
        ],
        [
            {"title": "High-voltage risk", "detail": "Serious safety training."},
            {"title": "Physical work", "detail": "Under the car, again."},
        ],
    ),
    _job(
        "renewable-energy-technician",
        "Wind Turbine Technician",
        "engineering-mechanical",
        "Installs and maintains wind turbines.",
        ["hands-electricity", "society-environment", "hands-machines"],
        ["mechanical-repair", "physical-stamina", "electronics"],
        ["physics"],
        _ws(teamwork=3, activity=PhysicalActivity.ACTIVE),
        _edu(EducationLevel.VOCATIONAL, ["wind-energy"]),
        {
            "activity": PhysicalActivity.ACTIVE,
            "requirements": ["heights", "physical-labor", "outdoor-conditions"],
        },
        _salary([32000, 45000], [55000, 80000], [80000, 105000]),
        {"outlook": "hot", "note": "Fastest-growing US job class.", "sources": {}},
        [Environment.OUTDOORS],
        [
            {"title": "Green mission", "detail": "Build the energy transition."},
            {"title": "Climbing pay", "detail": "Demand outstrips supply."},
        ],
        [
            {"title": "Height work", "detail": "100m ladders in wind."},
            {"title": "Remote sites", "detail": "Travel to turbines."},
        ],
    ),
]

RELATIONS: list[dict] = [
    {
        "from": "software-developer",
        "to": "ml-engineer",
        "type": "specialises_into",
        "weight": 0.8,
        "rationale": "Strong programming base leads into AI engineering.",
    },
    {
        "from": "data-scientist",
        "to": "ml-engineer",
        "type": "alternative_to",
        "weight": 0.7,
        "rationale": "Both model data; engineering vs analysis emphasis.",
    },
    {
        "from": "software-developer",
        "to": "data-scientist",
        "type": "similar_to",
        "weight": 0.6,
        "rationale": "Shared coding and statistics core.",
    },
    {
        "from": "software-developer",
        "to": "game-developer",
        "type": "alternative_to",
        "weight": 0.6,
        "rationale": "Same coding skills, different product passion.",
    },
    {
        "from": "software-developer",
        "to": "devops-engineer",
        "type": "leads_to",
        "weight": 0.7,
        "rationale": "Devs who love infrastructure become DevOps.",
    },
    {
        "from": "devops-engineer",
        "to": "cybersecurity-analyst",
        "type": "similar_to",
        "weight": 0.6,
        "rationale": "Systems knowledge transfers to security.",
    },
    {
        "from": "nurse",
        "to": "physician",
        "type": "leads_to",
        "weight": 0.4,
        "rationale": "Clinical experience can motivate medical school.",
    },
    {
        "from": "paramedic",
        "to": "nurse",
        "type": "leads_to",
        "weight": 0.7,
        "rationale": "Common bridge from emergency care into nursing.",
    },
    {
        "from": "nurse",
        "to": "physiotherapist",
        "type": "similar_to",
        "weight": 0.6,
        "rationale": "Patient-centred care in adjacent modalities.",
    },
    {
        "from": "psychologist",
        "to": "physician",
        "type": "prerequisite_of",
        "weight": 0.2,
        "rationale": "Different paths; psychology is not a medical prerequisite.",
    },
    {
        "from": "medical-lab-technician",
        "to": "pharmacist",
        "type": "leads_to",
        "weight": 0.4,
        "rationale": "Lab foundation supports pharmacy studies.",
    },
    {
        "from": "teacher",
        "to": "special-education-teacher",
        "type": "specialises_into",
        "weight": 0.8,
        "rationale": "General teaching specialises into SEN.",
    },
    {
        "from": "civil-engineer",
        "to": "architect",
        "type": "alternative_to",
        "weight": 0.5,
        "rationale": "Built environment; engineering vs design lead.",
    },
    {
        "from": "electrician",
        "to": "electric-vehicle-technician",
        "type": "leads_to",
        "weight": 0.7,
        "rationale": "Electrical mastery extends to EV systems.",
    },
    {
        "from": "mechanical-engineer",
        "to": "robotics-technician",
        "type": "prerequisite_of",
        "weight": 0.5,
        "rationale": "Mechanical fundamentals underpin robotics.",
    },
    {
        "from": "electrician",
        "to": "renewable-energy-technician",
        "type": "leads_to",
        "weight": 0.7,
        "rationale": "Wiring skills transfer to wind/solar.",
    },
    {
        "from": "accountant",
        "to": "financial-analyst",
        "type": "leads_to",
        "weight": 0.6,
        "rationale": "Accounting feeds into investment analysis.",
    },
    {
        "from": "marketing-specialist",
        "to": "graphic-designer",
        "type": "similar_to",
        "weight": 0.5,
        "rationale": "Campaigns pair copy with visuals.",
    },
    {
        "from": "graphic-designer",
        "to": "ux-designer",
        "type": "leads_to",
        "weight": 0.7,
        "rationale": "Visual craft evolves into product design.",
    },
    {
        "from": "journalist",
        "to": "marketing-specialist",
        "type": "alternative_to",
        "weight": 0.5,
        "rationale": "Writing skills monetise in content marketing.",
    },
    {
        "from": "social-worker",
        "to": "psychologist",
        "type": "leads_to",
        "weight": 0.4,
        "rationale": "Case work inspires clinical training.",
    },
    {
        "from": "police-officer",
        "to": "lawyer",
        "type": "leads_to",
        "weight": 0.3,
        "rationale": "Field experience precedes law school for some.",
    },
    {
        "from": "biologist",
        "to": "wildlife-biologist",
        "type": "specialises_into",
        "weight": 0.8,
        "rationale": "Biology specialises into ecology/zoology.",
    },
    {
        "from": "chemist",
        "to": "pharmacist",
        "type": "similar_to",
        "weight": 0.5,
        "rationale": "Chemistry core, applied vs clinical.",
    },
    {
        "from": "environmental-scientist",
        "to": "agronomist",
        "type": "similar_to",
        "weight": 0.6,
        "rationale": "Soil, sustainability and science overlap.",
    },
    {
        "from": "veterinary-technician",
        "to": "veterinarian",
        "type": "leads_to",
        "weight": 0.6,
        "rationale": "Tech experience strengthens vet applications.",
    },
    {
        "from": "farmer",
        "to": "agronomist",
        "type": "alternative_to",
        "weight": 0.4,
        "rationale": "Practical vs scientific crop expertise.",
    },
    {
        "from": "chef",
        "to": "hotel-manager",
        "type": "leads_to",
        "weight": 0.4,
        "rationale": "Kitchen leadership grows into broader hospitality.",
    },
    {
        "from": "logistics-coordinator",
        "to": "hotel-manager",
        "type": "alternative_to",
        "weight": 0.3,
        "rationale": "Operations management in different sectors.",
    },
    {
        "from": "pilot",
        "to": "firefighter",
        "type": "alternative_to",
        "weight": 0.2,
        "rationale": "Shared fitness and duty culture, different fields.",
    },
    {
        "from": "mechanical-engineer",
        "to": "renewable-energy-technician",
        "type": "similar_to",
        "weight": 0.5,
        "rationale": "Machines and energy systems.",
    },
    {
        "from": "teacher",
        "to": "psychologist",
        "type": "leads_to",
        "weight": 0.3,
        "rationale": "Educators often retrain in child psychology.",
    },
    {
        "from": "data-scientist",
        "to": "accountant",
        "type": "alternative_to",
        "weight": 0.3,
        "rationale": "Numeric roles with different cultures.",
    },
    {
        "from": "ux-designer",
        "to": "marketing-specialist",
        "type": "similar_to",
        "weight": 0.5,
        "rationale": "User empathy serves campaigns too.",
    },
]


PATHS: list[dict] = [
    {
        "job": "software-developer",
        "title": "The classic study route",
        "description": "Secondary school → CS degree → junior developer role.",
        "steps": [
            {
                "kind": "education",
                "education_level": "high_school",
                "label": "Focus on mathematics and computer science",
                "optional": False,
            },
            {
                "kind": "experience",
                "skill_key": "programming",
                "label": "Build small projects and join a coding club",
                "optional": False,
            },
            {
                "kind": "education",
                "family_key": "technology-software",
                "education_level": "bachelor",
                "label": "BSc in computer science or software engineering",
                "optional": False,
            },
            {
                "kind": "certification",
                "skill_key": "programming",
                "label": "Earn an entry-level programming certificate",
                "optional": True,
            },
            {
                "kind": "job",
                "family_key": "technology-software",
                "label": "Junior developer / internship role",
                "optional": False,
            },
        ],
    },
    {
        "job": "software-developer",
        "title": "The self-taught route",
        "description": "Skip the degree: portfolio-first entry via bootcamps and open source.",
        "steps": [
            {
                "kind": "education",
                "education_level": "high_school",
                "label": "Finish secondary school",
                "optional": False,
            },
            {
                "kind": "experience",
                "skill_key": "programming",
                "label": "Learn through online courses and open-source contributions",
                "optional": False,
            },
            {
                "kind": "certification",
                "skill_key": "problem-solving",
                "label": "Complete a recognised bootcamp or certification track",
                "optional": False,
            },
            {
                "kind": "job",
                "family_key": "technology-software",
                "label": "Apprentice / junior developer role",
                "optional": False,
            },
        ],
    },
    {
        "job": "data-scientist",
        "title": "The quantitative route",
        "description": "Strong maths foundation, then statistics or data science.",
        "steps": [
            {
                "kind": "education",
                "education_level": "high_school",
                "label": "Excel at mathematics and statistics courses",
                "optional": False,
            },
            {
                "kind": "education",
                "family_key": "technology-data",
                "education_level": "bachelor",
                "label": "BSc in statistics, mathematics or data science",
                "optional": False,
            },
            {
                "kind": "experience",
                "skill_key": "data-analysis",
                "label": "Portfolio projects analysing real datasets",
                "optional": False,
            },
            {
                "kind": "job",
                "family_key": "technology-data",
                "label": "Junior data analyst position",
                "optional": False,
            },
        ],
    },
    {
        "job": "physician",
        "title": "The medical school route",
        "description": "The long but direct path into clinical medicine.",
        "steps": [
            {
                "kind": "education",
                "education_level": "high_school",
                "label": "Strong grades in biology and chemistry",
                "optional": False,
            },
            {
                "kind": "education",
                "family_key": "healthcare-clinical",
                "education_level": "master",
                "label": "Medical degree (MD or equivalent)",
                "optional": False,
            },
            {
                "kind": "experience",
                "skill_key": "empathy",
                "label": "Hospital volunteering and clinical rotations",
                "optional": False,
            },
            {
                "kind": "certification",
                "skill_key": "first-aid",
                "label": "Medical licensing exams",
                "optional": False,
            },
            {
                "kind": "job",
                "family_key": "healthcare-clinical",
                "label": "Residency placement",
                "optional": False,
            },
        ],
    },
    {
        "job": "nurse",
        "title": "The caring professional route",
        "description": "Nursing degree with early patient exposure.",
        "steps": [
            {
                "kind": "education",
                "education_level": "high_school",
                "label": "Biology and care-related electives",
                "optional": False,
            },
            {
                "kind": "experience",
                "skill_key": "empathy",
                "label": "Care-home or first-aid volunteering",
                "optional": False,
            },
            {
                "kind": "education",
                "family_key": "healthcare-clinical",
                "education_level": "bachelor",
                "label": "BSc in nursing",
                "optional": False,
            },
            {
                "kind": "certification",
                "skill_key": "first-aid",
                "label": "Registered nurse licensing",
                "optional": False,
            },
        ],
    },
    {
        "job": "civil-engineer",
        "title": "The built-environment route",
        "description": "From physics class to construction sites.",
        "steps": [
            {
                "kind": "education",
                "education_level": "high_school",
                "label": "Mathematics and physics focus",
                "optional": False,
            },
            {
                "kind": "education",
                "family_key": "engineering-civil",
                "education_level": "bachelor",
                "label": "BSc in civil engineering",
                "optional": False,
            },
            {
                "kind": "experience",
                "skill_key": "engineering-design",
                "label": "CAD practice and site internships",
                "optional": False,
            },
            {
                "kind": "certification",
                "skill_key": "engineering-design",
                "label": "Professional engineering licence",
                "optional": True,
            },
        ],
    },
    {
        "job": "ux-designer",
        "title": "The design-thinker route",
        "description": "Human-centred design skills built through practice.",
        "steps": [
            {
                "kind": "education",
                "education_level": "high_school",
                "label": "Art, psychology and technology mix",
                "optional": False,
            },
            {
                "kind": "experience",
                "skill_key": "visual-design",
                "label": "Redesign familiar apps; build a case-study portfolio",
                "optional": False,
            },
            {
                "kind": "education",
                "family_key": "business-creative",
                "education_level": "bachelor",
                "label": "Degree in design, HCI or related field",
                "optional": True,
            },
            {
                "kind": "certification",
                "skill_key": "visual-design",
                "label": "UX certification or design-bootcamp certificate",
                "optional": True,
            },
            {
                "kind": "job",
                "family_key": "business-creative",
                "label": "Junior product/UX designer role",
                "optional": False,
            },
        ],
    },
    {
        "job": "veterinarian",
        "title": "The animal-care route",
        "description": "From shelter volunteering to veterinary medicine.",
        "steps": [
            {
                "kind": "education",
                "education_level": "high_school",
                "label": "Biology emphasis and animal-handling experience",
                "optional": False,
            },
            {
                "kind": "experience",
                "skill_key": "empathy",
                "label": "Volunteer at shelters or vet clinics",
                "optional": False,
            },
            {
                "kind": "education",
                "family_key": "agriculture",
                "education_level": "master",
                "label": "Veterinary medicine degree",
                "optional": False,
            },
            {
                "kind": "certification",
                "skill_key": "first-aid",
                "label": "Veterinary licensing exam",
                "optional": False,
            },
        ],
    },
]


# Typical years of relevant experience per job (min, max) — fit input (22).
EXPERIENCE_YEARS: dict[str, tuple[int, int]] = {
    "software-developer": (0, 2),
    "data-scientist": (1, 3),
    "ml-engineer": (2, 5),
    "cybersecurity-analyst": (1, 4),
    "devops-engineer": (2, 5),
    "game-developer": (0, 3),
    "nurse": (0, 2),
    "physician": (2, 6),
    "paramedic": (0, 3),
    "physiotherapist": (0, 3),
    "psychologist": (2, 5),
    "pharmacist": (0, 3),
    "medical-lab-technician": (0, 2),
    "teacher": (0, 2),
    "special-education-teacher": (1, 4),
    "civil-engineer": (1, 4),
    "electrician": (0, 4),
    "mechanical-engineer": (1, 4),
    "robotics-technician": (0, 3),
    "architect": (2, 5),
    "accountant": (0, 3),
    "financial-analyst": (1, 4),
    "marketing-specialist": (0, 3),
    "sales-representative": (0, 2),
    "graphic-designer": (0, 3),
    "ux-designer": (0, 3),
    "journalist": (0, 3),
    "police-officer": (0, 2),
    "firefighter": (0, 2),
    "lawyer": (2, 5),
    "social-worker": (0, 3),
    "environmental-scientist": (1, 4),
    "biologist": (1, 4),
    "chemist": (1, 4),
    "wildlife-biologist": (1, 4),
    "veterinarian": (1, 4),
    "veterinary-technician": (0, 2),
    "agronomist": (0, 3),
    "farmer": (0, 5),
    "chef": (1, 5),
    "hotel-manager": (1, 5),
    "logistics-coordinator": (0, 3),
    "pilot": (2, 6),
    "electric-vehicle-technician": (0, 3),
    "renewable-energy-technician": (0, 3),
}
